// Auto-generated by /design-sync — named re-exports of every design-system component.
// (Components use `export default`; a barrel is required so the IIFE bundle exposes them by name.)
export { default as BoundingBoxEditor } from './src/components/BoundingBoxEditor.jsx';
export { default as ChatbotPanel } from './src/components/ChatbotPanel.jsx';
export { default as ImageSelectorModal } from './src/components/ImageSelectorModal.jsx';
export { default as MultiBlockEditor } from './src/components/MultiBlockEditor.jsx';
export { default as NavBar } from './src/components/NavBar.jsx';
export { default as PhraseGenerator } from './src/components/PhraseGenerator.jsx';
export { default as PostCard } from './src/components/PostCard.jsx';
export { default as PostDetailPage } from './src/components/PostDetailPage.jsx';
export { default as PostFeedCard } from './src/components/PostFeedCard.jsx';
export { default as PostSuggestionPanel } from './src/components/PostSuggestionPanel.jsx';
export { default as RegionDetectorModal } from './src/components/RegionDetectorModal.jsx';
export { default as RichTextBlock } from './src/components/RichTextBlock.jsx';
export { default as StoryFlow } from './src/components/StoryFlow.jsx';
export { default as TagFilter } from './src/components/TagFilter.jsx';
export { default as TextPostCard } from './src/components/TextPostCard.jsx';
export { default as ThemeToggle } from './src/components/ThemeToggle.jsx';
export { default as TipTapEditor } from './src/components/TipTapEditor.jsx';
export { default as UntaggedImagesSidebar } from './src/components/UntaggedImagesSidebar.jsx';
export { default as UploadForm } from './src/components/UploadForm.jsx';
// Providers used by cfg.provider for preview context (not synced as components):
export { ThemeProvider } from './src/context/ThemeContext.jsx';
export { MemoryRouter } from 'react-router-dom';
