"""
PERCEPTUAL-ORGANS-002 Lane C — what the Topology façade is allowed to say, and what it must refuse.

The suite is organised by the CLAIMS the lane has to earn rather than by the functions it happens
to have, because the deliverable is not "seven operations run" — it is that a person can believe
what comes back:

    direction        `nested_within` and `contains` are one measurement read from two ends, and
                     swapping the endpoints swaps the word
    symmetry         `meets` reads the same both ways; the contact FRACTION does not, and the key
                     says whose perimeter it is of
    consistency      `disjoint` means one thing in every operation that can say it
    ceilings         a mask relation may be `measured`; a box relation may not, however confident
    absence          measured-and-nothing, refused, and never-run are three different records
    identity         every endpoint resolves back to an input, with its revision
    isolation        no Extent call, no Depth model, no database, no post

The mutation tests at the end are the other half. Each one breaks a specific rule and asserts the
break is caught — a law nothing fails on is a comment.

The controls are synthetic and committed: rectangles on a 40x60 raster, generated by
`scripts/perception_lab_topology_fixtures.py`, whose answers are known before the organ runs.
"""
from __future__ import annotations

import copy
import dataclasses
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import pytest

from backend.schemas.perception_lab import (ArtifactKind, EpistemicBasis, EpistemicStatus,
                                            IdentityScope, LabelSource, LifecycleState,
                                            PerceptualArtifact, ProducerKind, ProjectionKind,
                                            RefusalCode, RelationKind, RunOutcome)
from backend.services import adjacency_organ as adjacency_organ
from backend.services import depth_organ
from backend.services import nestedness_organ as nestedness_organ
from backend.services import occlusion_organ as occlusion_organ
from backend.services.perception_lab import definitions as D
from backend.services.perception_lab import topology as T
from backend.services.perception_lab import topology_evidence as ev

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_DIR = REPO_ROOT / "research" / "perception_lab" / "fixtures" / "topology"
FIXTURE_SCRIPT = REPO_ROOT / "scripts" / "perception_lab_topology_fixtures.py"

DIGEST = "sha256:70909a17c0d5e4b2"
NOW = "2026-08-10T12:00:00Z"


def fixture(name: str) -> Dict[str, Any]:
    return json.loads((FIXTURE_DIR / name).read_text(encoding="utf-8"))


def context(**over: Any) -> T.LabContext:
    base = dict(session_id="labs_topology", run_id="run_1", step_id="step_1",
                source_image_digest=DIGEST, now=NOW)
    base.update(over)
    return T.LabContext(**base)


def pair(operation: str, artifact: Dict[str, Any], source: str, target: str,
         *, parameters: Optional[Dict[str, Any]] = None,
         extras: Sequence[Dict[str, Any]] = (), **over: Any) -> T.TopologyRequest:
    art_id = artifact["identity"]["artifact_id"]
    return T.TopologyRequest(
        operation=operation, context=context(),
        inputs=(T.TopologyInput(role="source", artifact_id=art_id, instance_id=source),
                T.TopologyInput(role="target", artifact_id=art_id, instance_id=target)),
        parameters=parameters or {}, extents=(artifact, *extras), **over)


def members(operation: str, artifact: Dict[str, Any], instance_ids: Sequence[str], *,
            role: str = "members", parameters: Optional[Dict[str, Any]] = None
            ) -> T.TopologyRequest:
    art_id = artifact["identity"]["artifact_id"]
    return T.TopologyRequest(
        operation=operation, context=context(),
        inputs=tuple(T.TopologyInput(role=role, artifact_id=art_id, instance_id=i)
                     for i in instance_ids),
        parameters=parameters or {}, extents=(artifact,))


def relations(result: T.TopologyResult) -> List[Any]:
    assert not result.refused, f"unexpected refusal: {result.refusal}"
    return list(result.artifact.measurement.payload.relations)


def only(result: T.TopologyResult) -> Any:
    found = relations(result)
    assert len(found) == 1, f"expected one relation, got {[r.kind.value for r in found]}"
    return found[0]


# ── the artifact is contract-shaped, whatever it says ────────────────────────

ALL_OPERATIONS = ("topology.containment", "topology.adjacency", "topology.overlap",
                  "topology.disjoint", "topology.negative_space", "topology.all_pairs",
                  "topology.occlusion")


def every_operation_once() -> List[Tuple[str, T.TopologyResult]]:
    """One successful run of each of the seven operations, over the controls that suit them."""
    containment = fixture("extent-set.containment.json")
    contact = fixture("extent-set.contact.json")
    overlap = fixture("extent-set.overlap.json")
    apart = fixture("extent-set.disjoint.json")
    scene = fixture("extent-set.scene.json")
    depth = fixture("depth-field.inner-in-front.json")
    return [
        ("topology.containment",
         T.run(pair("topology.containment", containment, "inst_inner", "inst_outer"))),
        ("topology.adjacency",
         T.run(pair("topology.adjacency", contact, "inst_left", "inst_right"))),
        ("topology.overlap", T.run(pair("topology.overlap", overlap, "inst_a", "inst_b"))),
        ("topology.disjoint", T.run(pair("topology.disjoint", apart, "inst_a", "inst_b"))),
        ("topology.negative_space",
         T.run(members("topology.negative_space", containment, ["inst_inner"], role="figure"))),
        ("topology.all_pairs",
         T.run(members("topology.all_pairs", scene,
                       ["inst_outer", "inst_inner", "inst_touching", "inst_far"]))),
        ("topology.occlusion",
         T.run(dataclasses.replace(
             pair("topology.occlusion", containment, "inst_inner", "inst_outer"),
             depth=T.DepthArtifact(artifact_id=depth["artifact_id"], field=depth["field"])))),
    ]


def test_every_operation_produces_a_contract_valid_artifact():
    """The merged contract is the gate, and it is applied to the JSON rather than to the object.

    Round-tripped through JSON on purpose: Lane E reads what crosses the wire, and a model that
    validates in memory while serialising to something the schema rejects would pass a weaker test
    than the one that matters.
    """
    for operation, result in every_operation_once():
        assert not result.refused, f"{operation} refused: {result.refusal}"
        as_json = json.loads(result.artifact.model_dump_json())
        again = PerceptualArtifact.model_validate(as_json)
        assert again.identity.operation == operation
        assert again.identity.organ_family.value == "topology"
        assert again.identity.artifact_kind in (ArtifactKind.TOPOLOGY_RELATION_SET,
                                                ArtifactKind.NEGATIVE_SPACE_FIELD)
        assert again.provenance.producer == T.PRODUCER
        assert again.provenance.producer_kind is ProducerKind.ADAPTER
        assert again.lifecycle.status is LifecycleState.PROPOSED, \
            "a façade proposes; `kept` is a person's word"


def test_the_artifact_carries_no_label_and_no_review():
    """This organ reads pixels and never a name, so it has nothing to call what it measured."""
    for _, result in every_operation_once():
        interpretation = result.artifact.interpretation
        assert interpretation.label is None
        assert interpretation.label_source is LabelSource.NONE
        assert interpretation.epistemic_status is EpistemicStatus.UNCERTAIN
        assert not hasattr(result.artifact, "review")


def test_projection_hints_carry_no_geometry():
    """A projection able to hold a mask is a projection able to replace the evidence it depicts."""
    for _, result in every_operation_once():
        hints = result.artifact.projection.hints
        assert set(hints) <= {"opacity", "stroke_weight", "palette_role", "emphasis", "z_order",
                              "label_anchor", "legend"}
        assert "mask_rle" not in hints and "box" not in hints


def test_each_operation_proposes_a_projection_its_contract_declares():
    for operation, result in every_operation_once():
        declared = D.operation(operation).render_projections
        assert result.artifact.projection.projection_kind.value in declared


# ── containment: the direction IS the claim ──────────────────────────────────


def test_containment_measures_the_inner_shape_within_the_outer_one():
    result = T.run(pair("topology.containment", fixture("extent-set.containment.json"),
                        "inst_inner", "inst_outer"))
    relation = only(result)
    assert relation.kind is RelationKind.NESTED_WITHIN
    assert relation.directed is True
    assert relation.source.instance_id == "inst_inner"
    assert relation.target.instance_id == "inst_outer"
    assert relation.measurements["containment"] == 1.0
    assert relation.measurements["scale_ratio"] < nestedness_organ.MAX_SCALE_RATIO


def test_containment_read_from_the_other_end_is_the_other_word():
    """Swap the endpoints and the same geometry becomes `contains`. THE DIRECTIONALITY TEST.

    A façade that reported one relation kind whichever way round it was asked would be answering a
    question about a pair rather than about an arrow, and a person correcting the endpoints of a
    `nested_within` would have no way to say which shape they thought was inside.
    """
    reversed_result = T.run(pair("topology.containment", fixture("extent-set.containment.json"),
                                 "inst_outer", "inst_inner"))
    relation = only(reversed_result)
    assert relation.kind is RelationKind.CONTAINS
    assert relation.source.instance_id == "inst_outer"
    assert relation.target.instance_id == "inst_inner"
    assert relation.directed is True


def test_containment_carries_the_boundary_clearance_a_person_can_look_at():
    """The number is the finding; the locus is what makes it checkable against the picture."""
    relation = only(T.run(pair("topology.containment", fixture("extent-set.containment.json"),
                               "inst_inner", "inst_outer")))
    for key in ("boundary_clearance_px", "boundary_clearance_normalized",
                "boundary_nearest_x", "boundary_nearest_y"):
        assert key in relation.measurements
    assert relation.measurements["boundary_clearance_px"] > 0, \
        "the inner rectangle sits ten pixels clear of the outer one's edge"
    assert 0.0 <= relation.measurements["boundary_nearest_x"] <= 1.0
    assert 0.0 <= relation.measurements["boundary_nearest_y"] <= 1.0


def test_containment_reports_the_thresholds_it_judged_against():
    relation = only(T.run(pair("topology.containment", fixture("extent-set.containment.json"),
                               "inst_inner", "inst_outer")))
    assert relation.measurements["threshold_min_containment"] == nestedness_organ.MIN_CONTAINMENT
    assert relation.measurements["threshold_max_scale_ratio"] == nestedness_organ.MAX_SCALE_RATIO


# ── adjacency: symmetric in kind, asymmetric in number ───────────────────────


def test_adjacency_finds_the_contact_and_its_locus():
    relation = only(T.run(pair("topology.adjacency", fixture("extent-set.contact.json"),
                               "inst_left", "inst_right")))
    assert relation.kind is RelationKind.MEETS
    assert relation.directed is False, "`meets` reads the same in both directions"
    assert relation.measurements["contact_pixels"] > 0
    assert relation.measurements["contact_fraction_of_source_perimeter"] >= \
        adjacency_organ.MIN_CONTACT
    assert relation.measurements["contact_locus_h"] > relation.measurements["contact_locus_w"], \
        "two rectangles sharing a column meet along a tall, narrow band"


def test_adjacency_is_symmetric_in_kind_and_asymmetric_in_number():
    """THE SYMMETRY TEST, and the half of it that is not symmetric.

    Whether two shapes meet does not depend on which is named first. HOW MUCH of a shape's own
    perimeter lies in the contact does — a small shape against a large one meets along most of
    itself and a sliver of the other — so the number is named for whose perimeter it measures.
    """
    contact = fixture("extent-set.contact.json")
    forward = only(T.run(pair("topology.adjacency", contact, "inst_left", "inst_right")))
    backward = only(T.run(pair("topology.adjacency", contact, "inst_right", "inst_left")))
    assert forward.kind is backward.kind is RelationKind.MEETS
    assert forward.measurements["contact_pixels"] == backward.measurements["contact_pixels"]

    # Same contact, different perimeters: a taller shape against a wider one.
    scene = fixture("extent-set.scene.json")
    a = only(T.run(pair("topology.adjacency", scene, "inst_outer", "inst_touching")))
    b = only(T.run(pair("topology.adjacency", scene, "inst_touching", "inst_outer")))
    assert a.kind is b.kind is RelationKind.MEETS
    assert a.measurements["source_perimeter_pixels"] != b.measurements["source_perimeter_pixels"]
    assert a.measurements["contact_fraction_of_source_perimeter"] != \
        b.measurements["contact_fraction_of_source_perimeter"]


def test_adjacency_reports_a_pair_that_does_not_touch_as_a_positive_disjoint():
    """The contract's "positive no-relation": measured, and they are apart, with the distance."""
    relation = only(T.run(pair("topology.adjacency", fixture("extent-set.disjoint.json"),
                               "inst_a", "inst_b")))
    assert relation.kind is RelationKind.DISJOINT
    assert relation.measurements["clearance_px"] > 0
    assert relation.measurements["contact_pixels"] == 0


def test_adjacency_will_not_call_an_enclosed_pair_disjoint():
    """One shape inside another neither meets its edge nor stands apart from it.

    The most confident wrong answer available here: their boundaries never touch, so a naive
    adjacency reports `disjoint` — of a pair where one shape is entirely inside the other. The
    honest record is a measured emptiness that names the operation which does answer it.
    """
    result = T.run(pair("topology.adjacency", fixture("extent-set.containment.json"),
                        "inst_inner", "inst_outer"))
    assert not result.refused
    assert result.outcome is RunOutcome.EMPTY
    assert result.artifact.measurement.payload.relations == []
    assert result.artifact.measurement.payload.pairs_examined == 1
    assert "overlap" in (result.artifact.interpretation.notes or "")


def test_adjacency_tolerance_is_recorded_and_changes_what_touching_means():
    scene = fixture("extent-set.disjoint.json")
    strict = only(T.run(pair("topology.adjacency", scene, "inst_a", "inst_b")))
    assert strict.measurements["contact_tolerance_px"] == 0.0
    generous = only(T.run(pair("topology.adjacency", scene, "inst_a", "inst_b",
                               parameters={"contact_tolerance_px": 3})))
    assert generous.measurements["contact_tolerance_px"] == 3.0
    assert generous.kind is RelationKind.DISJOINT, "three pixels does not close a forty-pixel gap"


# ── overlap and disjointness: one meaning of the word ────────────────────────


def test_overlap_measures_the_exact_intersection_and_where_it_is():
    relation = only(T.run(pair("topology.overlap", fixture("extent-set.overlap.json"),
                               "inst_a", "inst_b")))
    assert relation.kind is RelationKind.OVERLAPS
    # Two 20x20 rectangles crossing over a 10x10 square: the arithmetic is checkable by hand.
    assert relation.measurements["intersection_pixels"] == 100.0
    assert relation.measurements["area_source_pixels"] == 400.0
    assert relation.measurements["iou"] == pytest.approx(100 / 700, abs=1e-6)
    assert relation.measurements["intersection_locus_w"] == pytest.approx(10 / 60, abs=1e-6)


def test_overlap_and_disjoint_agree_about_every_pair():
    """THE CONSISTENCY TEST. `disjoint` means no shared pixels AND no contact, in both operations.

    Run over every unordered pair of every control scene, so the agreement is a property of the
    vocabulary rather than of the one example that was easy to write.
    """
    scenes = {name: fixture(name) for name in
              ("extent-set.containment.json", "extent-set.contact.json",
               "extent-set.overlap.json", "extent-set.disjoint.json")}
    for name, artifact in scenes.items():
        ids = [i["instance_id"] for i in artifact["measurement"]["payload"]["instances"]]
        for a, b in ((ids[0], ids[1]), (ids[1], ids[0])):
            over = T.run(pair("topology.overlap", artifact, a, b))
            apart = T.run(pair("topology.disjoint", artifact, a, b))
            over_kinds = {r.kind for r in relations(over)}
            apart_kinds = {r.kind for r in relations(apart)}
            if RelationKind.DISJOINT in over_kinds:
                assert apart_kinds == {RelationKind.DISJOINT}, \
                    f"{name}: overlap says apart and disjoint does not"
            if RelationKind.DISJOINT in apart_kinds:
                assert RelationKind.OVERLAPS not in over_kinds, \
                    f"{name}: a pair reported both apart and overlapping"


def test_disjoint_measures_the_separation_and_the_nearest_approach():
    relation = only(T.run(pair("topology.disjoint", fixture("extent-set.disjoint.json"),
                               "inst_a", "inst_b")))
    assert relation.kind is RelationKind.DISJOINT
    assert relation.measurements["clearance_px"] > 30
    assert 0.0 < relation.measurements["clearance_normalized"] < 1.0
    assert 0.0 <= relation.measurements["nearest_x"] <= 1.0


def test_disjoint_reports_contact_as_meets_rather_than_forcing_its_own_name():
    relation = only(T.run(pair("topology.disjoint", fixture("extent-set.contact.json"),
                               "inst_left", "inst_right")))
    assert relation.kind is RelationKind.MEETS
    assert relation.measurements["contact_pixels"] > 0


def test_overlap_refuses_box_only_endpoints():
    """An intersection of two boxes is an intersection of two boxes.

    The founding pathology in miniature, and the contract forbids the basis rather than reporting
    it weakly — so this is a refusal, not an `interpretive` overlap.
    """
    result = T.run(pair("topology.overlap", fixture("extent-set.box-only.json"),
                        "inst_inner", "inst_outer"))
    assert result.refused
    assert result.refusal.code is RefusalCode.MISSING_EXTENT_INPUTS
    assert result.refusal.detail["reason"] == "box_basis_not_admissible"


# ── the two bases keep different ceilings ────────────────────────────────────


def test_a_box_basis_containment_may_not_be_measured_however_confident():
    """THE WAVE2.5 RULING, in the laboratory. The finial-in-the-sky number, and its ceiling.

    The box reading of these two rectangles is a containment of 1.000 — the same shape of number
    that made `cseg_golden_finial_7` read as nested inside the sky. It is still reported, because
    a person comparing substrates needs to see what the coarse one said. It is `interpretive`.
    """
    boxed = only(T.run(pair("topology.containment", fixture("extent-set.box-only.json"),
                            "inst_inner", "inst_outer")))
    masked = only(T.run(pair("topology.containment", fixture("extent-set.containment.json"),
                             "inst_inner", "inst_outer")))
    assert boxed.basis is EpistemicBasis.BOX
    assert boxed.epistemic_status is EpistemicStatus.INTERPRETIVE
    assert boxed.measurements["containment"] == pytest.approx(1.0, abs=1e-6)
    assert masked.basis is EpistemicBasis.MASK
    assert masked.epistemic_status is EpistemicStatus.MEASURED
    assert masked.measurements["containment"] == pytest.approx(1.0, abs=1e-6)
    assert boxed.epistemic_status is not masked.epistemic_status, \
        "identical numbers, different kinds of knowing — that is the whole ruling"


def test_the_artifacts_ceiling_matches_the_relations_it_carries():
    for scene, status, basis in (("extent-set.containment.json", EpistemicStatus.MEASURED,
                                  EpistemicBasis.MASK),
                                 ("extent-set.box-only.json", EpistemicStatus.INTERPRETIVE,
                                  EpistemicBasis.BOX)):
        result = T.run(pair("topology.containment", fixture(scene), "inst_inner", "inst_outer"))
        assert result.artifact.measurement.epistemic_basis is basis
        assert result.artifact.measurement.epistemic_status is status
        emphasis = result.artifact.projection.hints["emphasis"]
        assert emphasis == ("primary" if status is EpistemicStatus.MEASURED else "muted")


def test_asking_for_the_box_basis_on_maskable_geometry_gives_the_box_ceiling():
    """A person may ask the coarse substrate what it would have said. It answers, at its ceiling."""
    relation = only(T.run(pair("topology.containment", fixture("extent-set.containment.json"),
                               "inst_inner", "inst_outer", parameters={"basis": "box"})))
    assert relation.basis is EpistemicBasis.BOX
    assert relation.epistemic_status is EpistemicStatus.INTERPRETIVE


def test_asking_for_the_mask_basis_without_masks_refuses_rather_than_degrading():
    result = T.run(pair("topology.containment", fixture("extent-set.box-only.json"),
                        "inst_inner", "inst_outer", parameters={"basis": "mask"}))
    assert result.refused
    assert result.refusal.detail["reason"] == "mask_basis_requested_but_unavailable"


def test_two_masks_on_different_rasters_fall_back_rather_than_resampling():
    """Resampling one mask onto the other's grid would invent the pixels the answer is made of."""
    result = T.run(pair("topology.containment", fixture("extent-set.other-raster.json"),
                        "inst_full", "inst_small"))
    assert not result.refused
    assert result.artifact.measurement.epistemic_basis is EpistemicBasis.BOX
    assert result.artifact.measurement.epistemic_status is EpistemicStatus.INTERPRETIVE


# ── negative space ───────────────────────────────────────────────────────────


def test_negative_space_measures_the_ground_and_keeps_the_field_out_of_the_payload():
    result = T.run(members("topology.negative_space", fixture("extent-set.containment.json"),
                           ["inst_inner"], role="figure", parameters={"max_distance": 0.5}))
    payload = result.artifact.measurement.payload
    assert payload.figure_instance_ids == ["inst_inner"]
    assert payload.field_shape == [40, 60]
    assert payload.max_distance_used == 0.5
    assert payload.field_ref is None, "this lane has no store; Lane F attaches the pointer"
    # The inner rectangle is 100 of 2400 pixels, so the ground is the rest.
    assert payload.statistics["ground_fraction"] == pytest.approx(2300 / 2400, abs=1e-4)
    assert result.field_values is not None and len(result.field_values) == 40 * 60
    assert result.field_shape == (40, 60)


def test_the_negative_space_field_is_zero_on_the_figure_and_rises_away_from_it():
    result = T.run(members("topology.negative_space", fixture("extent-set.containment.json"),
                           ["inst_inner"], role="figure", parameters={"max_distance": 1.0}))
    field = result.field_values
    assert field is not None
    # (25, 20) is inside the inner rectangle (x 20..29, y 15..24); (0, 0) is the far corner.
    assert field[20 * 60 + 25] == 0.0
    assert field[0] > field[14 * 60 + 25] > 0.0, "distance rises with distance from the figure"


def test_negative_space_truncation_is_recorded_and_changes_the_field():
    figure = fixture("extent-set.containment.json")
    near = T.run(members("topology.negative_space", figure, ["inst_inner"], role="figure",
                         parameters={"max_distance": 0.05}))
    far = T.run(members("topology.negative_space", figure, ["inst_inner"], role="figure",
                        parameters={"max_distance": 1.0}))
    assert near.artifact.measurement.payload.max_distance_used == 0.05
    assert near.artifact.measurement.payload.statistics["saturated_fraction"] > \
        far.artifact.measurement.payload.statistics["saturated_fraction"], \
        "a tighter truncation saturates more of the ground"
    assert near.artifact.measurement.payload.statistics["max_clearance_normalized"] == \
        far.artifact.measurement.payload.statistics["max_clearance_normalized"], \
        "truncation changes the FIELD, not the measured depth of the ground"


def test_negative_space_takes_the_union_of_several_figures():
    scene = fixture("extent-set.scene.json")
    one = T.run(members("topology.negative_space", scene, ["inst_outer"], role="figure"))
    both = T.run(members("topology.negative_space", scene, ["inst_outer", "inst_far"],
                         role="figure"))
    assert both.artifact.measurement.payload.figure_instance_ids == ["inst_outer", "inst_far"]
    assert both.artifact.measurement.payload.statistics["ground_fraction"] < \
        one.artifact.measurement.payload.statistics["ground_fraction"]


def test_negative_space_refuses_a_figure_that_covers_the_whole_frame():
    """No ground is a fact about the geometry, not a field of zeros."""
    whole = copy.deepcopy(fixture("extent-set.containment.json"))
    instances = whole["measurement"]["payload"]["instances"]
    instances[0]["mask_rle"] = {"size": [40, 60], "counts": [0, 2400]}
    result = T.run(members("topology.negative_space", whole, ["inst_inner"], role="figure"))
    assert result.refused
    assert result.refusal.detail["reason"] == "no_negative_space"


# ── bounded all-pairs ────────────────────────────────────────────────────────


def test_all_pairs_walks_every_unordered_pair_of_the_selected_set():
    result = T.run(members("topology.all_pairs", fixture("extent-set.scene.json"),
                           ["inst_outer", "inst_inner", "inst_touching", "inst_far"]))
    payload = result.artifact.measurement.payload
    assert payload.pairs_examined == 6, "four members is six unordered pairs"
    assert payload.bounded_to == 4
    kinds = {r.kind for r in payload.relations}
    assert RelationKind.CONTAINS in kinds
    assert RelationKind.MEETS in kinds
    assert RelationKind.DISJOINT in kinds
    assert RelationKind.OVERLAPS in kinds


def test_all_pairs_never_widens_the_set_it_was_given():
    """`max_regions` bounds it; a person's selection bounds it; nothing here goes looking."""
    scene = fixture("extent-set.scene.json")
    bounded = T.run(members("topology.all_pairs", scene,
                            ["inst_outer", "inst_inner", "inst_touching", "inst_far"],
                            parameters={"max_regions": 2}))
    payload = bounded.artifact.measurement.payload
    assert payload.bounded_to == 2
    assert payload.pairs_examined == 1
    endpoints = {r.source.instance_id for r in payload.relations} | \
                {r.target.instance_id for r in payload.relations}
    assert endpoints <= {"inst_outer", "inst_inner"}


def test_all_pairs_measures_only_the_relation_families_it_was_asked_for():
    scene = fixture("extent-set.scene.json")
    result = T.run(members("topology.all_pairs", scene,
                           ["inst_outer", "inst_inner", "inst_touching"],
                           parameters={"relations": ["meets"]}))
    kinds = {r.kind for r in result.artifact.measurement.payload.relations}
    assert kinds == {RelationKind.MEETS}
    assert result.artifact.measurement.payload.pairs_examined == 3


def test_all_pairs_clamps_a_relation_kind_the_operation_does_not_declare():
    result = T.run(members("topology.all_pairs", fixture("extent-set.scene.json"),
                           ["inst_outer", "inst_inner"],
                           parameters={"relations": ["meets", "in_front_of"]}))
    clamped = {name for name, *_ in result.clamped_parameters}
    assert "relations" in clamped, "a kind this operation does not declare is dropped, and said so"
    kinds = {r.kind for r in result.artifact.measurement.payload.relations}
    assert RelationKind.IN_FRONT_OF not in kinds


def test_a_graph_with_one_box_edge_is_not_a_measured_graph():
    """The weaker basis governs the whole, exactly as `occlusion_organ` rules for a pair.

    Each relation keeps its own basis, so a reader can see which edges are which — but the artifact
    may not claim more than its weakest edge.
    """
    mixed = copy.deepcopy(fixture("extent-set.scene.json"))
    for inst in mixed["measurement"]["payload"]["instances"]:
        if inst["instance_id"] == "inst_far":
            inst["mask_rle"] = None                      # box only, from here on
    result = T.run(members("topology.all_pairs", mixed,
                           ["inst_outer", "inst_inner", "inst_far"]))
    assert result.artifact.measurement.epistemic_basis is EpistemicBasis.BOX
    assert result.artifact.measurement.epistemic_status is EpistemicStatus.INTERPRETIVE
    bases = {r.basis for r in result.artifact.measurement.payload.relations}
    assert EpistemicBasis.MASK in bases, "the mask edges keep their own, stronger basis"


def test_all_pairs_needs_at_least_two_members():
    result = T.run(members("topology.all_pairs", fixture("extent-set.scene.json"), ["inst_outer"]))
    assert result.refused
    assert result.refusal.code is RefusalCode.MISSING_EXTENT_INPUTS


# ── absence: three records that must not collapse ────────────────────────────


def test_a_measured_no_relation_is_not_a_refusal_and_not_a_not_run():
    """THE ABSENCE TEST. Three different nothings, three different records.

        measured emptiness   an artifact, `pairs_examined: 1`, outcome `empty`
        a refusal            a refusal ARTIFACT with a typed code, outcome `refused`
        never run            no artifact at all — and this lane cannot produce that record
    """
    apart = fixture("extent-set.disjoint.json")
    measured = T.run(pair("topology.containment", apart, "inst_a", "inst_b"))
    assert not measured.refused
    assert measured.outcome is RunOutcome.EMPTY
    assert measured.artifact.identity.artifact_kind is ArtifactKind.TOPOLOGY_RELATION_SET
    assert measured.artifact.measurement.payload.pairs_examined == 1
    assert measured.artifact.measurement.payload.relations == []

    refused = T.run(T.TopologyRequest(
        operation="topology.containment", context=context(),
        inputs=(T.TopologyInput(role="source", artifact_id="art_topo_disjoint",
                                instance_id="inst_a"),),
        extents=(apart,)))
    assert refused.refused
    assert refused.outcome is RunOutcome.REFUSED
    assert refused.artifact.identity.artifact_kind is ArtifactKind.REFUSAL
    assert refused.refusal.code is RefusalCode.MISSING_EXTENT_INPUTS

    assert measured.artifact.measurement.payload_variant != \
        refused.artifact.measurement.payload_variant


def test_the_empty_payload_cannot_be_written_without_saying_what_was_examined():
    """`relations: []` with nothing counted is not a measurement, and the record forbids it."""
    from pydantic import ValidationError

    from backend.schemas.perception_lab import TopologyRelationSetPayload
    with pytest.raises(ValidationError):
        TopologyRelationSetPayload(variant="topology_relation_set", pairs_examined=0,
                                   relations=[])


def test_a_refusal_is_an_artifact_with_a_place_in_the_ledger():
    result = T.run(pair("topology.overlap", fixture("extent-set.box-only.json"),
                        "inst_inner", "inst_outer"))
    artifact = result.artifact
    assert artifact.identity.run_id == "run_1" and artifact.identity.step_id == "step_1"
    assert artifact.measurement.epistemic_status is EpistemicStatus.UNCERTAIN
    assert artifact.measurement.epistemic_basis is EpistemicBasis.DECLARED
    assert artifact.projection.projection_kind is ProjectionKind.NONE
    assert artifact.measurement.payload.refusal.code is RefusalCode.MISSING_EXTENT_INPUTS
    PerceptualArtifact.model_validate(json.loads(artifact.model_dump_json()))


# ── refusals: empty masks, missing and dangling endpoints ────────────────────


def test_an_empty_mask_refuses_rather_than_measuring_nothing():
    """A valid RLE that sets no pixels. There is nowhere in the picture for an endpoint to be."""
    result = T.run(pair("topology.overlap", fixture("extent-set.empty-mask.json"),
                        "inst_empty", "inst_solid"))
    assert result.refused
    assert result.refusal.code is RefusalCode.MISSING_EXTENT_INPUTS
    assert result.refusal.detail["reason"] == "empty_mask"


@pytest.mark.parametrize("operation", ["topology.containment", "topology.adjacency",
                                       "topology.overlap", "topology.disjoint"])
def test_a_missing_endpoint_refuses_in_every_pair_operation(operation):
    result = T.run(T.TopologyRequest(
        operation=operation, context=context(),
        inputs=(T.TopologyInput(role="source", artifact_id="art_topo_overlap",
                                instance_id="inst_a"),),
        extents=(fixture("extent-set.overlap.json"),)))
    assert result.refused
    assert result.refusal.code is RefusalCode.MISSING_EXTENT_INPUTS
    assert "target" in result.refusal.missing


def test_no_inputs_at_all_refuses_missing_extent_inputs():
    result = T.run(T.TopologyRequest(operation="topology.adjacency", context=context()))
    assert result.refused
    assert result.refusal.code is RefusalCode.MISSING_EXTENT_INPUTS


def test_a_dangling_artifact_reference_refuses_unknown_reference():
    result = T.run(T.TopologyRequest(
        operation="topology.overlap", context=context(),
        inputs=(T.TopologyInput(role="source", artifact_id="art_nobody_supplied"),
                T.TopologyInput(role="target", artifact_id="art_topo_overlap",
                                instance_id="inst_b")),
        extents=(fixture("extent-set.overlap.json"),)))
    assert result.refused
    assert result.refusal.code is RefusalCode.UNKNOWN_REFERENCE
    assert result.refusal.detail["reason"] == "dangling_artifact"


def test_a_dangling_instance_reference_refuses_and_says_what_was_available():
    result = T.run(pair("topology.overlap", fixture("extent-set.overlap.json"),
                        "inst_a", "inst_that_never_was"))
    assert result.refused
    assert result.refusal.code is RefusalCode.UNKNOWN_REFERENCE
    assert result.refusal.detail["reason"] == "dangling_instance"
    assert result.refusal.detail["available"] == ["inst_a", "inst_b"]


def test_an_artifact_of_several_instances_will_not_be_guessed_at():
    """A laboratory that picked the first mask would answer about one nobody selected."""
    result = T.run(T.TopologyRequest(
        operation="topology.overlap", context=context(),
        inputs=(T.TopologyInput(role="source", artifact_id="art_topo_overlap"),
                T.TopologyInput(role="target", artifact_id="art_topo_overlap",
                                instance_id="inst_b")),
        extents=(fixture("extent-set.overlap.json"),)))
    assert result.refused
    assert result.refusal.detail["reason"] == "ambiguous_instance"


def test_an_operation_of_another_organ_is_organ_locked_and_has_no_artifact():
    """A CONTRACT BOUNDARY, found by trying to cross it.

    `PerceptualArtifact` requires `identity.operation` to be a declared operation of the organ that
    produced it, so a refusal about `extent.find_all` has no artifact it could legally inhabit —
    a topology artifact naming an extent operation does not validate, and it should not. These two
    refusals are plan-time facts about a request that was never a topology operation, and they
    belong in `LabPlan.refusals` / `LabRun.refusals`, which is where Lane A put refusal lists.
    """
    result = T.run(T.TopologyRequest(operation="extent.find_all", context=context()))
    assert result.refused
    assert result.refusal.code is RefusalCode.ORGAN_LOCKED
    assert result.refusal.detail["operation_organ"] == "extent"
    assert result.artifact is None


def test_an_operation_nobody_declares_is_unsupported_and_has_no_artifact():
    result = T.run(T.TopologyRequest(operation="topology.invent_a_relation", context=context()))
    assert result.refused
    assert result.refusal.code is RefusalCode.UNSUPPORTED_OPERATION
    assert result.artifact is None


def test_every_refusal_a_declared_operation_raises_still_gets_its_artifact():
    """The boundary above is the only one. Inside the organ, a refusal is a record in the ledger."""
    for result in (T.run(T.TopologyRequest(operation="topology.overlap", context=context())),
                   T.run(pair("topology.overlap", fixture("extent-set.box-only.json"),
                              "inst_inner", "inst_outer")),
                   T.run(occlusion_request(None))):
        assert result.refused
        assert result.artifact is not None
        assert result.artifact.identity.artifact_kind is ArtifactKind.REFUSAL


def test_a_parameter_of_the_wrong_type_refuses_and_an_undeclared_one_is_dropped():
    bad = T.run(pair("topology.adjacency", fixture("extent-set.contact.json"),
                     "inst_left", "inst_right", parameters={"contact_tolerance_px": "two"}))
    assert bad.refused and bad.refusal.code is RefusalCode.INVALID_PARAMETERS

    smuggled = T.run(pair("topology.adjacency", fixture("extent-set.contact.json"),
                          "inst_left", "inst_right",
                          parameters={"mask_rle": {"size": [1, 1], "counts": [1]}}))
    assert not smuggled.refused
    assert [name for name, _ in smuggled.dropped_parameters] == ["mask_rle"]


def test_a_clamped_parameter_is_recorded_rather_than_refused():
    result = T.run(pair("topology.adjacency", fixture("extent-set.contact.json"),
                        "inst_left", "inst_right", parameters={"contact_tolerance_px": 999}))
    assert not result.refused
    assert [name for name, *_ in result.clamped_parameters] == ["contact_tolerance_px"]
    assert result.parameters_used["contact_tolerance_px"] == 32


# ── identity: every endpoint resolves, with its revision ─────────────────────


def supplied_instances(*artifacts: Dict[str, Any]) -> Dict[Tuple[str, str], Dict[str, Any]]:
    out: Dict[Tuple[str, str], Dict[str, Any]] = {}
    for artifact in artifacts:
        art_id = artifact["identity"]["artifact_id"]
        for inst in artifact["measurement"]["payload"]["instances"]:
            out[(art_id, inst["instance_id"])] = inst
    return out


def test_every_returned_endpoint_resolves_to_an_input_identity_and_revision():
    """THE IDENTITY TEST, over every operation that returns relations.

    A relation cites endpoints and never carries the mask it measured, so the citation is the only
    thing tying the number back to the picture. An endpoint that resolved to nothing — or to a
    region without saying which revision of it — would be a relation nobody could check or
    invalidate.
    """
    known = supplied_instances(fixture("extent-set.containment.json"),
                               fixture("extent-set.contact.json"),
                               fixture("extent-set.overlap.json"),
                               fixture("extent-set.disjoint.json"),
                               fixture("extent-set.scene.json"),
                               fixture("extent-set.canonical.json"))
    for operation, result in every_operation_once():
        if result.artifact.identity.artifact_kind is not ArtifactKind.TOPOLOGY_RELATION_SET:
            continue
        for relation in result.artifact.measurement.payload.relations:
            for endpoint in (relation.source, relation.target):
                key = (endpoint.artifact_id, endpoint.instance_id)
                assert key in known, f"{operation} cited an endpoint nobody supplied: {key}"
                supplied = known[key]
                assert endpoint.region_id == supplied["region_id"]
                assert endpoint.geometry_rev == supplied["geometry_rev"]
                if endpoint.scope is IdentityScope.CANONICAL:
                    assert endpoint.region_id and endpoint.geometry_rev is not None


def test_a_canonical_endpoint_carries_its_region_and_revision_into_the_artifact():
    result = T.run(pair("topology.containment", fixture("extent-set.canonical.json"),
                        "inst_finial", "inst_sky"))
    relation = only(result)
    assert relation.source.scope is IdentityScope.CANONICAL
    assert (relation.source.region_id, relation.source.geometry_rev) == ("reg_finial_7", 4)
    assert (relation.target.region_id, relation.target.geometry_rev) == ("reg_sky_1", 2)
    refs = {(r.region_id, r.geometry_rev) for r in result.artifact.identity.identity_refs}
    assert refs == {("reg_finial_7", 4), ("reg_sky_1", 2)}
    assert result.artifact.identity.identity_scope is IdentityScope.SESSION, \
        "the artifact is the lab's; the endpoints may be Semant's"


def test_a_newer_revision_of_an_endpoint_makes_the_relation_visibly_stale():
    canonical = fixture("extent-set.canonical.json")
    fresh = T.run(pair("topology.containment", canonical, "inst_finial", "inst_sky"))
    assert only(fresh).stale is False
    stale = T.run(dataclasses.replace(
        pair("topology.containment", canonical, "inst_finial", "inst_sky"),
        current_region_revs={"reg_finial_7": 5}))
    assert only(stale).stale is True


def test_supplying_a_region_at_the_wrong_revision_refuses():
    """Two revisions of one region are two shapes, and the seam may not be used to swap them."""
    result = T.run(dataclasses.replace(
        pair("topology.containment", fixture("extent-set.canonical.json"),
             "inst_finial", "inst_sky"),
        regions=({"id": "reg_finial_7", "geometry_rev": 9,
                  "mask_rle": {"size": [40, 60], "counts": [0, 2400]}},)))
    assert result.refused
    assert result.refusal.code is RefusalCode.UNKNOWN_REFERENCE
    assert result.refusal.detail["reason"] == "revision_mismatch"


def test_an_explicitly_supplied_region_at_the_cited_revision_provides_the_geometry():
    """The explicit-region seam: a reuse instance may cite a region the caller holds the mask for."""
    coarse = copy.deepcopy(fixture("extent-set.canonical.json"))
    for inst in coarse["measurement"]["payload"]["instances"]:
        if inst["instance_id"] == "inst_finial":
            inst["mask_rle"] = None                     # a box-only projection of a masked Region
    without = T.run(pair("topology.containment", coarse, "inst_finial", "inst_sky"))
    assert without.artifact.measurement.epistemic_basis is EpistemicBasis.BOX

    real_mask = fixture("extent-set.canonical.json")["measurement"]["payload"]["instances"][0]
    with_region = T.run(dataclasses.replace(
        pair("topology.containment", coarse, "inst_finial", "inst_sky"),
        regions=({"id": "reg_finial_7", "geometry_rev": 4,
                  "mask_rle": real_mask["mask_rle"]},)))
    assert with_region.artifact.measurement.epistemic_basis is EpistemicBasis.MASK
    assert only(with_region).epistemic_status is EpistemicStatus.MEASURED


def test_relation_ids_are_stable_across_identical_repeats_and_differ_across_steps():
    """A person comparing two repeats is comparing relations, not lining up two sets of uuids."""
    request = pair("topology.overlap", fixture("extent-set.overlap.json"), "inst_a", "inst_b")
    first = only(T.run(request)).relation_id
    second = only(T.run(request)).relation_id
    assert first == second

    other_step = dataclasses.replace(request, context=context(step_id="step_2"))
    assert only(T.run(other_step)).relation_id != first
    assert T.run(other_step).artifact.identity.artifact_id != T.run(request).artifact.identity.artifact_id


# ── occlusion: a supplied field, or a typed refusal ──────────────────────────


def occlusion_request(depth_fixture: Optional[str] = "depth-field.inner-in-front.json",
                      scene: str = "extent-set.containment.json") -> T.TopologyRequest:
    request = pair("topology.occlusion", fixture(scene), "inst_inner", "inst_outer")
    if depth_fixture is None:
        return request
    depth = fixture(depth_fixture)
    return dataclasses.replace(request, depth=T.DepthArtifact(artifact_id=depth["artifact_id"],
                                                              field=depth["field"]))


def test_occlusion_orders_the_pair_from_the_supplied_field():
    relation = only(T.run(occlusion_request()))
    assert relation.kind is RelationKind.IN_FRONT_OF
    assert relation.directed is True
    assert relation.source.instance_id == "inst_inner", "the nearer shape is the source"
    assert relation.target.instance_id == "inst_outer"
    assert relation.basis is EpistemicBasis.DEPTH_ARTIFACT
    assert relation.epistemic_status is EpistemicStatus.MEASURED
    assert relation.measurements["separation"] >= occlusion_organ.MIN_SEPARATION


def test_occlusion_names_the_field_it_read_and_that_it_did_not_compute_one():
    result = T.run(occlusion_request())
    detail = result.artifact.measurement.basis_detail
    assert "depth_inner_in_front" in detail
    assert "cannot" in detail
    assert result.artifact.provenance.adapter == "occlusion_organ"


def test_occlusion_with_a_field_that_orders_nothing_reports_coplanar_not_containment():
    """`coplanar` is not `inside`. Depth cannot see containment, and this refuses to imply it."""
    relation = only(T.run(occlusion_request("depth-field.flat.json")))
    assert relation.kind is RelationKind.COPLANAR
    assert relation.directed is False
    assert relation.measurements["separation"] < occlusion_organ.MIN_SEPARATION


def test_missing_depth_produces_the_typed_refusal_and_nothing_else():
    """THE DEPENDENCY TEST. `missing_depth_artifact`, naming what would satisfy it."""
    result = T.run(occlusion_request(None))
    assert result.refused
    assert result.outcome is RunOutcome.REFUSED
    assert result.refusal.code is RefusalCode.MISSING_DEPTH_ARTIFACT
    assert result.refusal.missing == ["depth"]
    assert result.refusal.detail["artifact_kinds"] == ["depth_field"]
    assert result.artifact.identity.artifact_kind is ArtifactKind.REFUSAL
    assert "does not compute one" in result.refusal.message


def test_a_depth_field_from_another_model_is_refused_rather_than_read():
    result = T.run(occlusion_request("depth-field.foreign-adapter.json"))
    assert result.refused
    assert result.refusal.code is RefusalCode.INVALID_PARAMETERS
    assert result.refusal.detail["reason"] == "occlusion_refusal"


def test_occlusion_refuses_box_only_endpoints():
    """A box's depth averages a thing with whatever it occludes — the pathology as its own evidence."""
    depth = fixture("depth-field.inner-in-front.json")
    result = T.run(dataclasses.replace(
        pair("topology.occlusion", fixture("extent-set.box-only.json"),
             "inst_inner", "inst_outer"),
        depth=T.DepthArtifact(artifact_id=depth["artifact_id"], field=depth["field"])))
    assert result.refused
    assert result.refusal.detail["reason"] == "box_basis_not_admissible"


def test_occlusion_cannot_invoke_depth(monkeypatch):
    """THE ISOLATION TEST. The one function that turns a model estimate into a field is a landmine.

    `depth_organ.depth_field` is the ONLY constructor of the thing occlusion reads. If this façade
    could ever satisfy its own dependency it would go through here, so replacing it with a raising
    stub and watching a full occlusion run succeed is the proof: the field came from the caller.
    """
    def landmine(*args, **kwargs):                      # pragma: no cover - it must not be reached
        raise AssertionError("the topology façade constructed a depth field")

    monkeypatch.setattr(depth_organ, "depth_field", landmine)
    relation = only(T.run(occlusion_request()))
    assert relation.kind is RelationKind.IN_FRONT_OF


def test_the_lab_cannot_mint_a_depth_field_artifact_at_all():
    """Lane A's ruling, restated where this lane would have to break it: `depth_field` is
    declarable, suppliable, and producible by nothing in this phase."""
    assert "depth_field" not in D.producible_artifact_kinds()
    assert "depth_field" in D.organ("topology").consumes_artifact_kinds
    declaration = D.operation("topology.occlusion").dependency_declaration
    assert declaration["may_invoke"] is False
    assert declaration["refusal_when_missing"] == "missing_depth_artifact"


# ── isolation: no Extent, no Depth model, no database, no post ───────────────

_SUBPROCESS_PROBE = """
import json, sys
sys.path.insert(0, {repo!r})
from backend.services.perception_lab import topology as T

F = {fixtures!r}
load = lambda n: json.load(open(F + "/" + n))
ctx = T.LabContext(session_id="s", run_id="r", step_id="p",
                   source_image_digest="sha256:70909a17c0d5e4b2", now="2026-08-10T12:00:00Z")
scene = load("extent-set.containment.json")
contact = load("extent-set.contact.json")
depth = load("depth-field.inner-in-front.json")

def two(op, art, a, b, **kw):
    return T.TopologyRequest(operation=op, context=ctx, extents=(art,), inputs=(
        T.TopologyInput(role="source", artifact_id=art["identity"]["artifact_id"], instance_id=a),
        T.TopologyInput(role="target", artifact_id=art["identity"]["artifact_id"], instance_id=b),
    ), **kw)

outcomes = []
outcomes.append(T.run(two("topology.containment", scene, "inst_inner", "inst_outer")).outcome.value)
outcomes.append(T.run(two("topology.adjacency", contact, "inst_left", "inst_right")).outcome.value)
outcomes.append(T.run(two("topology.overlap", scene, "inst_inner", "inst_outer")).outcome.value)
outcomes.append(T.run(two("topology.disjoint", scene, "inst_inner", "inst_outer")).outcome.value)
outcomes.append(T.run(T.TopologyRequest(operation="topology.negative_space", context=ctx,
    extents=(scene,), inputs=(T.TopologyInput(role="figure",
        artifact_id="art_topo_containment", instance_id="inst_inner"),))).outcome.value)
outcomes.append(T.run(T.TopologyRequest(operation="topology.all_pairs", context=ctx,
    extents=(scene,), inputs=tuple(T.TopologyInput(role="members",
        artifact_id="art_topo_containment", instance_id=i)
        for i in ("inst_inner", "inst_outer")))).outcome.value)
outcomes.append(T.run(two("topology.occlusion", scene, "inst_inner", "inst_outer",
    depth=T.DepthArtifact(artifact_id=depth["artifact_id"], field=depth["field"]))).outcome.value)

print(json.dumps({{
    "outcomes": outcomes,
    "loaded": sorted(m for m in T.FORBIDDEN_MODULES if m in sys.modules),
    "torch": "torch" in sys.modules,
}}))
"""


def test_a_full_topology_run_imports_no_model_no_segmenter_and_no_database():
    """THE NON-MUTATION TEST, taken at the import graph rather than at the call site.

    A subprocess, because `sys.modules` in a long test session is full of everything every other
    test imported. Here nothing is loaded but this façade, and if a database handle or a model
    service appears while seven operations run, it appeared because this lane reached for it.
    """
    probe = _SUBPROCESS_PROBE.format(repo=str(REPO_ROOT), fixtures=str(FIXTURE_DIR))
    done = subprocess.run([sys.executable, "-c", probe], capture_output=True, text=True,
                          cwd=str(REPO_ROOT))
    assert done.returncode == 0, done.stderr
    report = json.loads(done.stdout.strip().splitlines()[-1])
    assert report["loaded"] == [], f"the façade reached for {report['loaded']}"
    assert report["torch"] is False, "no model stack is loaded by a topology run"
    assert set(report["outcomes"]) <= {"ready", "empty"}


def test_the_façade_never_mutates_what_it_was_handed():
    """Artifacts, regions and depth fields go in; the caller's objects come out unchanged.

    Not a matter of taste: a session holds one extent artifact and several runs read it, and an
    organ that normalised a mask in place would make the second run a measurement of the first.
    """
    scene = fixture("extent-set.containment.json")
    depth = fixture("depth-field.inner-in-front.json")
    regions = [{"id": "reg_finial_7", "geometry_rev": 4}]
    before = copy.deepcopy((scene, depth, regions))

    request = dataclasses.replace(
        pair("topology.containment", scene, "inst_inner", "inst_outer"),
        regions=tuple(regions))
    T.run(request)
    T.run(dataclasses.replace(request, operation="topology.overlap"))
    T.run(dataclasses.replace(
        request, operation="topology.occlusion",
        depth=T.DepthArtifact(artifact_id=depth["artifact_id"], field=depth["field"])))

    assert (scene, depth, regions) == before


def test_the_organ_regions_handed_to_the_adapters_are_copies():
    """The adapters take mappings and this lane promises not to give them the caller's."""
    endpoint = T._Endpoint(role="source", artifact_id="a", instance_id="i",
                           scope=IdentityScope.SESSION, region_id=None, geometry_rev=None,
                           mask_rle={"size": [2, 2], "counts": [0, 4]}, box=None, stale=False)
    region = endpoint.as_region()
    region["mask_rle"]["counts"] = [4]
    assert endpoint.mask_rle["counts"] == [0, 4]


def test_the_forbidden_module_list_is_not_empty_and_names_the_real_ones():
    """A guard whose list is empty passes forever."""
    assert "backend.services.depth_service" in T.FORBIDDEN_MODULES
    assert "backend.database" in T.FORBIDDEN_MODULES
    for name in T.FORBIDDEN_MODULES:
        parts = name.split(".")
        path = REPO_ROOT.joinpath(*parts)
        assert path.with_suffix(".py").exists() or path.is_dir(), \
            f"{name} is not a module in this tree — the guard is watching a ghost"


# ── the vocabulary is reconciled, not renamed ────────────────────────────────


def test_the_relation_kinds_are_the_strings_the_organs_already_emit():
    assert RelationKind.NESTED_WITHIN.value == nestedness_organ.RELATION_NESTED_WITHIN
    assert RelationKind.MEETS.value == adjacency_organ.RELATION_MEETS
    assert RelationKind.IN_FRONT_OF.value == occlusion_organ.RELATION_IN_FRONT_OF
    assert RelationKind.COPLANAR.value == occlusion_organ.RELATION_COPLANAR


def test_every_declared_topology_operation_has_a_runner():
    assert set(T.RUNNERS) == {op.key for op in D.operations_for("topology")}


def test_every_operation_only_uses_an_adapter_its_contract_declares():
    for operation, adapter in T.PRIMARY_ADAPTER.items():
        assert adapter in D.operation(operation).adapters


def test_the_committed_controls_have_not_drifted_from_their_generator():
    done = subprocess.run([sys.executable, str(FIXTURE_SCRIPT), "--check"],
                          capture_output=True, text=True, cwd=str(REPO_ROOT))
    assert done.returncode == 0, done.stdout + done.stderr


# ── mutation tests: break a rule, watch it fail ──────────────────────────────


def test_mutation_raising_the_containment_threshold_unmakes_the_relation(monkeypatch):
    """THRESHOLD MUTATION. The façade reads the organ's floor; it does not keep a copy.

    A copy would drift, and a laboratory whose reported threshold and applied threshold were two
    different numbers would be lying in the most convincing way available: with a receipt.
    """
    before = only(T.run(pair("topology.containment", fixture("extent-set.containment.json"),
                             "inst_inner", "inst_outer")))
    assert before.kind is RelationKind.NESTED_WITHIN

    monkeypatch.setattr(nestedness_organ, "MIN_CONTAINMENT", 1.01)
    after = T.run(pair("topology.containment", fixture("extent-set.containment.json"),
                       "inst_inner", "inst_outer"))
    assert after.artifact.measurement.payload.relations == [], \
        "a floor nothing can clear must leave nothing nested"
    assert after.outcome is RunOutcome.EMPTY


def test_mutation_raising_the_contact_threshold_turns_meeting_into_apartness(monkeypatch):
    monkeypatch.setattr(adjacency_organ, "MIN_CONTACT", 0.99)
    relation = only(T.run(pair("topology.adjacency", fixture("extent-set.contact.json"),
                               "inst_left", "inst_right")))
    assert relation.kind is RelationKind.DISJOINT
    assert relation.measurements["threshold_min_contact"] == 0.99, \
        "the receipt reports the floor that was actually applied"


def test_mutation_raising_the_separation_floor_turns_in_front_of_into_coplanar(monkeypatch):
    monkeypatch.setattr(occlusion_organ, "MIN_SEPARATION", 0.999)
    relation = only(T.run(occlusion_request()))
    assert relation.kind is RelationKind.COPLANAR


def test_mutation_a_direction_ignoring_containment_would_fail_this(monkeypatch):
    """DIRECTION MUTATION. Force the reverse reading to be taken as the forward one and watch the
    endpoints stop matching the word."""
    real = nestedness_organ.measure

    def swapped(inner, outer, **kwargs):
        return real(outer, inner, **kwargs)

    monkeypatch.setattr(nestedness_organ, "measure", swapped)
    result = T.run(pair("topology.containment", fixture("extent-set.containment.json"),
                        "inst_inner", "inst_outer"))
    relation = only(result)
    assert relation.kind is RelationKind.CONTAINS, \
        "with the organ's arguments swapped the façade reports the other word — which is what it " \
        "means for the direction to come from the measurement rather than from the argument order"


def test_mutation_a_missing_input_treated_as_empty_would_fail_this():
    """MISSING-INPUT MUTATION. The difference between `refused` and `empty` is the deliverable.

    Written as an assertion about the RECORD rather than about a mutated function, because the
    mutation being guarded against is a caller reading one for the other: an artifact kind, an
    outcome and a payload variant all have to move together for a refusal to masquerade as a
    measurement.
    """
    refused = T.run(T.TopologyRequest(operation="topology.overlap", context=context()))
    assert refused.outcome is RunOutcome.REFUSED
    assert refused.artifact.identity.artifact_kind is ArtifactKind.REFUSAL
    assert refused.artifact.measurement.payload_variant == "refusal"
    assert not hasattr(refused.artifact.measurement.payload, "pairs_examined")


def test_mutation_a_box_relation_claiming_measured_does_not_validate():
    """The record itself refuses it, so no façade bug can publish one."""
    from pydantic import ValidationError

    from backend.schemas.perception_lab import RelationEndpoint, TopologyRelation
    endpoint = RelationEndpoint(artifact_id="a", instance_id="i", scope=IdentityScope.SESSION)
    with pytest.raises(ValidationError):
        TopologyRelation(relation_id="r", kind=RelationKind.NESTED_WITHIN, source=endpoint,
                         target=endpoint, directed=True, basis=EpistemicBasis.BOX,
                         epistemic_status=EpistemicStatus.MEASURED)


def test_mutation_an_empty_mask_read_as_a_zero_area_extent_would_fail_this():
    with pytest.raises(ev.GeometryUnavailable):
        ev.decode({"size": [40, 60], "counts": [2400]})


def test_mutation_masks_on_two_rasters_may_not_be_compared():
    a = ev.decode({"size": [4, 4], "counts": [0, 16]})
    b = ev.decode({"size": [2, 8], "counts": [0, 16]})
    with pytest.raises(ev.GeometryUnavailable):
        ev.same_raster(a, b)
