"""
PERCEPTUAL-FORMS-001D — what the structural Topology forms are allowed to say.

Organised by the CLAIMS these producers have to earn, not by the functions they happen to have.
The deliverable is not "four producers run"; it is that a person reading a tree, a graph, a
transition or a conditional set can believe what it says AND can see what it left out:

    direction      a nesting means the same thing in both spellings, and the tree is the same tree
    reduction      a redundant ancestor is ABSORBED by transitivity, never deleted
    disagreement   cycles and incomparable parents are reported, never broken or chosen between
    identity       a node is `artifact_id#instance_id`. A label never merges two of them, and a
                   revision never mints a third
    bounds         a declared member with no edges stays visible; an undeclared endpoint is refused
    revision       a transition cites four pinned references, and a threshold crossing is a change
                   in the RELATION and not in the object
    hypotheses     every conditional relation keeps its condition, no kind is ever averaged, and
                   no reading is dropped for being unlikely
    ceilings       box basis stays interpretive; a composition never outruns its weakest input
    isolation      no Extent call, no Depth call, no database, no post — proved on the import
                   closure rather than promised in a docstring

THE CONTROLS ARE SYNTHETIC AND COMMITTED, generated by
`scripts/perception_lab_topology_form_fixtures.py`: rectangles on a 40x60 raster whose structure is
known before the organ runs, each written twice — as the `extent_set` a topology operation consumes
and as the `topology_relation_set` the façade measured from it. The suite runs the generator's
`--check` by name, so a scene edited and not regenerated fails here rather than drifting quietly.

The mutation tests at the end are the other half. Each deletes one guard and asserts the deletion
turns a named test red — a law nothing fails on is a comment.
"""
from __future__ import annotations

import ast
import copy
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import pytest

from backend.schemas.perception_lab import (BASIS_CEILINGS, PARTITION_CEILINGS, STATUS_ORDER,
                                            EpistemicBasis, EpistemicPartition, EpistemicStatus,
                                            ExtentHypothesisSetPayload, PerceptualArtifact,
                                            RefusalCode, RelationKind, TopologyContactLocusPayload,
                                            TopologyContainmentTreePayload, TransitionChange)
from backend.services.perception_lab import definitions as D
from backend.services.perception_lab.topology_forms import adjacency as A
from backend.services.perception_lab.topology_forms import containment as C
from backend.services.perception_lab.topology_forms import transition as X
from backend.services.perception_lab.topology_forms import uncertain as U
from backend.services.perception_lab.topology_forms.sources import Roster, endpoint_key

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_DIR = REPO_ROOT / "research" / "perception_lab" / "fixtures" / "topology_forms"
FIXTURE_SCRIPT = REPO_ROOT / "scripts" / "perception_lab_topology_form_fixtures.py"


def fixture(name: str) -> Dict[str, Any]:
    return json.loads((FIXTURE_DIR / name).read_text(encoding="utf-8"))


def key(artifact: str, instance: str) -> str:
    return f"{artifact}#{instance}"


FOREST = "art_forms_forest"
PIERS = "art_forms_piers"
AMBIGUOUS = "art_forms_ambiguous"


# ── building relation sets by hand, for the cases geometry cannot produce ────


def relation(kind: str, source: str, target: str, *, artifact: str = FOREST,
             relation_id: Optional[str] = None, basis: str = "mask",
             status: str = "measured", directed: bool = True,
             measurements: Optional[Dict[str, float]] = None,
             source_artifact: Optional[str] = None,
             target_artifact: Optional[str] = None) -> Dict[str, Any]:
    """One relation, as JSON. Used where a real scene cannot make the case.

    A CONTAINMENT CYCLE IS THE MOTIVATING EXAMPLE, and it is worth saying why it must be
    hand-written. `nestedness_organ` will not report A inside B and B inside A off one raster —
    `MAX_SCALE_RATIO` forbids it. A cycle in the wild arrives the other way: two measurements taken
    at different revisions, on different bases, or in different runs, composed afterwards. Which is
    exactly what these producers do, and exactly why they have to survive it.
    """
    return {
        "relation_id": relation_id or f"rel_{kind}_{source}_{target}",
        "kind": kind,
        "source": {"artifact_id": source_artifact or artifact, "instance_id": source,
                   "scope": "session", "region_id": None, "geometry_rev": None},
        "target": {"artifact_id": target_artifact or artifact, "instance_id": target,
                   "scope": "session", "region_id": None, "geometry_rev": None},
        "directed": directed, "basis": basis, "epistemic_status": status,
        "measurements": measurements or {}, "stale": False,
    }


def relation_artifact(relations: Sequence[Dict[str, Any]], *, pairs_examined: int,
                      artifact_id: str = "art_hand_relations", basis: str = "mask",
                      status: str = "measured") -> Dict[str, Any]:
    """A contract-shaped `topology.pair_relation` artifact around hand-written relations.

    Built by replacing the payload of a generated control rather than typed out, so that a change
    to the artifact envelope shows up in one place instead of in every hand-made case.
    """
    doc = copy.deepcopy(fixture("relations.forest.json"))
    doc["identity"]["artifact_id"] = artifact_id
    doc["identity"]["identity_refs"] = []
    doc["measurement"]["payload"] = {"variant": "topology_relation_set",
                                     "pairs_examined": pairs_examined,
                                     "relations": list(relations), "bounded_to": None}
    doc["measurement"]["epistemic_basis"] = basis
    doc["measurement"]["epistemic_status"] = status
    return PerceptualArtifact.model_validate(doc).model_dump(mode="json")


def inverted(doc: Dict[str, Any]) -> Dict[str, Any]:
    """The same relation set, every nesting spelled from the other end.

    `contains(A→B)` and `nested_within(B→A)` are one measurement read from two sides. This swaps
    the spelling without touching the measurement, which is what lets the direction law be tested
    as an EQUIVALENCE rather than as two separate assertions that happen to agree.
    """
    out = copy.deepcopy(doc)
    flip = {"contains": "nested_within", "nested_within": "contains"}
    for rel in out["measurement"]["payload"]["relations"]:
        if rel["kind"] in flip:
            rel["kind"] = flip[rel["kind"]]
            rel["source"], rel["target"] = rel["target"], rel["source"]
    return out


def S_locus(*, key_a: str, key_b: str) -> TopologyContactLocusPayload:
    """A recorded contact band for one pair.

    Built as a payload rather than an artifact, and that is not a shortcut: `topology.contact_locus`
    is produced by no operation, so `PerceptualArtifact` refuses to carry one and there is no
    arrangement of this fixture that could be an artifact today.
    """
    def end(key: str) -> Dict[str, Any]:
        artifact_id, instance_id = key.split("#")
        return {"artifact_id": artifact_id, "instance_id": instance_id, "scope": "session",
                "region_id": None, "geometry_rev": None}
    return TopologyContactLocusPayload.model_validate({
        "variant": "topology_contact_locus", "pairs_examined": 1,
        "loci": [{"locus_id": "locus_1", "source": end(key_a), "target": end(key_b),
                  "raster_shape": [40, 60], "contact_pixels": 24, "basis": "mask",
                  "epistemic_status": "measured",
                  "mask_rle": {"size": [40, 60], "counts": [1200, 24, 1176]},
                  "points": [[0.26, 0.1], [0.26, 0.5]]}]})


def tree(*sets: Dict[str, Any], roster: Optional[Roster] = None) -> C.ContainmentReading:
    return C.produce_containment_tree(list(sets), roster=roster)


def parents(reading: C.ContainmentReading) -> Dict[str, Optional[str]]:
    return {n.node_id: n.parent_node_id for n in reading.payload.nodes}


# ── the controls are the controls ────────────────────────────────────────────


def test_the_committed_controls_are_what_the_generator_builds():
    """`--check` by name, so a scene edited and not regenerated fails here.

    It is also a drift alarm on `topology.py`: the relation sets are what the real façade measured
    from the real scenes, so a change in how a relation is recorded reaches this suite as a diff a
    person reads rather than as a silent change in what the composition was tested against.
    """
    done = subprocess.run([sys.executable, str(FIXTURE_SCRIPT), "--check"],
                          capture_output=True, text=True, cwd=str(REPO_ROOT))
    assert done.returncode == 0, done.stderr


def test_every_control_is_a_contract_valid_artifact():
    for path in sorted(FIXTURE_DIR.glob("*.json")):
        again = PerceptualArtifact.model_validate(json.loads(path.read_text(encoding="utf-8")))
        assert again.identity.organ_family.value in ("extent", "topology")


# ── the forest: what nesting composes into ───────────────────────────────────


def test_the_nested_forest_composes_into_two_roots_and_three_levels():
    reading = tree(fixture("relations.forest.json"))
    assert reading.producible, "containment_tree is `experimental`, not deferred"
    assert set(reading.payload.root_node_ids) == {key(FOREST, "court"), key(FOREST, "wall")}
    assert parents(reading) == {
        key(FOREST, "court"): None,
        key(FOREST, "fountain"): key(FOREST, "court"),
        key(FOREST, "basin"): key(FOREST, "fountain"),
        key(FOREST, "wall"): None,
        key(FOREST, "niche"): key(FOREST, "wall"),
    }


def test_the_occupancy_is_quoted_from_the_measurement_and_never_recomputed():
    """`scale_ratio` is `area(inner) / area(outer)`, measured by `nestedness_organ`.

    The basin is 4x4 in a 12x10 fountain: 16/120. A producer that recomputed it from areas would
    be making a measurement, and this lane does not make measurements.
    """
    reading = tree(fixture("relations.forest.json"))
    by_id = {n.node_id: n for n in reading.payload.nodes}
    assert by_id[key(FOREST, "basin")].occupancy_of_parent == pytest.approx(16 / 120, abs=1e-6)
    assert by_id[key(FOREST, "fountain")].occupancy_of_parent == pytest.approx(120 / 1064,
                                                                              abs=1e-6)
    for root in reading.payload.root_node_ids:
        assert by_id[root].occupancy_of_parent is None, "a root occupies no parent"


def test_a_nesting_means_the_same_thing_spelled_from_either_end():
    """The direction law, as an equivalence. `contains(A→B)` and `nested_within(B→A)` are one
    measurement, so the two spellings must build one tree."""
    forward = tree(fixture("relations.forest.json"))
    backward = tree(inverted(fixture("relations.forest.json")))
    assert parents(forward) == parents(backward)
    assert forward.payload.root_node_ids == backward.payload.root_node_ids


def test_the_redundant_ancestor_is_absorbed_by_transitivity_and_not_deleted():
    """`court ⊃ basin` was measured AND is implied by `court ⊃ fountain ⊃ basin`.

    The tree holds the NEARER holder, and the reader still reads basin inside court by walking. The
    absorbed relation is named, because "this edge is redundant" and "this edge was dropped" look
    identical from outside and only one of them is true.
    """
    reading = tree(fixture("relations.forest.json"))
    absorbed = [r for r in fixture("relations.forest.json")["measurement"]["payload"]["relations"]
                if r["kind"] == "contains" and r["source"]["instance_id"] == "court"
                and r["target"]["instance_id"] == "basin"]
    assert len(absorbed) == 1
    assert reading.implied == (absorbed[0]["relation_id"],)
    assert not reading.omissions_for("containment_conflict")

    walk, node = [], key(FOREST, "basin")
    by_id = {n.node_id: n for n in reading.payload.nodes}
    while node is not None:
        walk.append(node)
        node = by_id[node].parent_node_id
    assert walk == [key(FOREST, "basin"), key(FOREST, "fountain"), key(FOREST, "court")]


def test_pairs_examined_is_carried_through_rather_than_recounted():
    """Ten pairs were compared for the forest. A composition that recounted from the relations it
    received would report a number about itself, and `pairs_examined` is the field that separates a
    measured emptiness from an absence of measurement."""
    reading = tree(fixture("relations.forest.json"))
    assert reading.payload.pairs_examined == 10

    nothing = tree(relation_artifact([], pairs_examined=6))
    assert nothing.payload.pairs_examined == 6, "six pairs were compared and nothing nested"
    assert nothing.payload.nodes == []


# ── disagreement: never broken, never chosen between ─────────────────────────


def test_two_incomparable_holders_exclude_the_node_and_name_both():
    """One shape inside two overlapping shapes that contain neither.

    `ContainmentNode` holds ONE parent, so there is no arrangement of this record that can say
    where `inner` is. Both candidates are named in a conflict and the node leaves.
    """
    reading = tree(fixture("relations.ambiguous.json"))
    inner = key(AMBIGUOUS, "inner")
    assert inner not in parents(reading)
    conflict, = [c for c in reading.conflicts if c.kind == "ambiguous_parents"]
    assert conflict.node_key == inner
    assert conflict.candidates == (key(AMBIGUOUS, "left_hall"), key(AMBIGUOUS, "right_hall"))
    assert len(conflict.relation_ids) == 2
    assert [o.what for o in reading.omissions_for("containment_conflict")] == [inner]


def test_a_disputed_node_is_never_parked_at_the_root():
    """The tempting move, and the one that would turn an ambiguity into a finding.

    `root_node_ids` means "nothing holds it". A node whose holders are in dispute is held by two
    things, and listing it as a root would report top-level-ness that two measurements contradict.
    """
    reading = tree(fixture("relations.ambiguous.json"))
    assert key(AMBIGUOUS, "inner") not in reading.payload.root_node_ids
    assert set(reading.payload.root_node_ids) == {key(AMBIGUOUS, "left_hall"),
                                                 key(AMBIGUOUS, "right_hall")}


def test_a_containment_cycle_is_reported_and_never_broken():
    """A ⊂ B ⊂ A means two measurements disagree. Breaking it would hide the disagreement, and
    Lane A's `_acyclic` will not validate a payload that contains one."""
    doc = relation_artifact([relation("contains", "a", "b"), relation("contains", "b", "a")],
                            pairs_examined=1)
    reading = tree(doc)
    assert reading.payload.nodes == [], "neither end of a contradiction may stand in the tree"
    cycled = {c.node_key for c in reading.conflicts if c.kind == "cycle"}
    assert cycled == {key(FOREST, "a"), key(FOREST, "b")}, "the whole cycle, not an entry point"
    assert {o.what for o in reading.omissions_for("containment_cycle")} == cycled


def test_a_longer_cycle_names_every_node_on_it():
    doc = relation_artifact([relation("contains", "a", "b"), relation("contains", "b", "c"),
                             relation("contains", "c", "a")], pairs_examined=3)
    reading = tree(doc)
    assert {c.node_key for c in reading.conflicts if c.kind == "cycle"} == {
        key(FOREST, "a"), key(FOREST, "b"), key(FOREST, "c")}


def test_excluding_a_node_excludes_what_hung_from_it():
    """The cascade. `deep` is inside `inner`, whose holders are in dispute.

    Leaving `deep` behind pointing at a node the record no longer holds would not validate, and
    re-rooting it would claim a top-level-ness the relations contradict just as loudly as the
    dispute they contradict.
    """
    doc = relation_artifact([relation("contains", "left", "inner"),
                             relation("contains", "right", "inner"),
                             relation("contains", "inner", "deep")], pairs_examined=3)
    reading = tree(doc)
    held = set(parents(reading))
    assert key(FOREST, "inner") not in held
    assert key(FOREST, "deep") not in held
    assert [o.what for o in reading.omissions_for("orphaned_by_exclusion")] == [key(FOREST, "deep")]
    assert set(reading.payload.root_node_ids) == {key(FOREST, "left"), key(FOREST, "right")}


def test_a_node_held_only_by_a_cycle_leaves_with_it():
    doc = relation_artifact([relation("contains", "a", "b"), relation("contains", "b", "a"),
                             relation("contains", "b", "child")], pairs_examined=3)
    reading = tree(doc)
    assert parents(reading) == {}, "nothing here is held by anything the record can stand behind"
    assert [o.what for o in reading.omissions_for("orphaned_by_exclusion")] == [
        key(FOREST, "child")]


# ── bounds, and endpoints that are not there ─────────────────────────────────


def test_a_relation_citing_an_endpoint_outside_the_roster_is_refused():
    """A roster is the caller's declaration of what this structure may hold, read off the extent
    artifacts they supplied. A nesting over an endpoint nobody supplied would be a structure about
    something this record cannot show."""
    roster = Roster.of([fixture("extent-set.forest.json")])
    doc = relation_artifact([relation("contains", "court", "ghost")], pairs_examined=1)
    reading = tree(doc, roster=roster)
    refusal, = reading.refusals
    assert refusal.code is RefusalCode.UNKNOWN_REFERENCE
    assert key(FOREST, "ghost") in refusal.message
    assert [o.what for o in reading.omissions_for("endpoint_dangling")] == [key(FOREST, "ghost")]
    assert reading.payload.nodes == [], "the relation contributed no edge"


def test_without_a_roster_nothing_can_dangle_and_that_is_not_the_same_as_admitting_it():
    """Absent a declared bound, a structure is over exactly what its relations cite. There is no
    roster to fall outside of, so there is no dangling reference — and the two situations are told
    apart by whether a roster was given, never by a default."""
    doc = relation_artifact([relation("contains", "court", "ghost")], pairs_examined=1)
    reading = tree(doc)
    assert reading.refusals == ()
    assert set(parents(reading)) == {key(FOREST, "court"), key(FOREST, "ghost")}


def test_a_shape_inside_itself_is_not_a_level_of_a_nesting():
    doc = relation_artifact([relation("contains", "a", "a")], pairs_examined=1)
    reading = tree(doc)
    assert reading.payload.nodes == []
    assert [o.reason for o in reading.omitted] == ["self_pair"]


def test_relations_that_are_not_nestings_are_named_rather_than_ignored():
    """The forest control carries `overlaps` and `disjoint` too. A producer that silently skipped
    them would report the same tree as one that had never been handed them."""
    reading = tree(fixture("relations.forest.json"))
    skipped = reading.omissions_for("not_a_structural_kind")
    assert len(skipped) == 10, "four overlaps and six disjoints"
    assert all("is not a nesting" in o.detail for o in skipped)


# ── the ceilings a composition may not climb ─────────────────────────────────


def test_a_box_basis_nesting_stays_interpretive_however_confident_it_is():
    doc = relation_artifact([relation("contains", "outer", "inner", basis="box",
                                      status="interpretive",
                                      measurements={"scale_ratio": 0.02, "containment": 0.999})],
                            pairs_examined=1, basis="box", status="interpretive")
    reading = tree(doc)
    node = next(n for n in reading.payload.nodes if n.parent_node_id is not None)
    assert node.basis is EpistemicBasis.BOX
    assert node.epistemic_status is EpistemicStatus.INTERPRETIVE
    assert reading.ceiling is EpistemicStatus.INTERPRETIVE
    assert BASIS_CEILINGS[EpistemicBasis.BOX] is EpistemicStatus.INTERPRETIVE


def test_a_composition_never_outruns_the_weakest_artifact_under_it():
    """`exact_derivation` is capped by its inputs, and that cap needs the inputs in hand — which is
    why it is asked of `derived_ceiling` and recorded on the production rather than left to a
    validator looking at one record."""
    weak = relation_artifact([relation("contains", "a", "b", basis="box", status="interpretive",
                                       measurements={"scale_ratio": 0.1})],
                             pairs_examined=1, artifact_id="art_weak", basis="box",
                             status="interpretive")
    strong = fixture("relations.forest.json")
    reading = tree(strong, weak)
    assert reading.input_statuses == (EpistemicStatus.MEASURED, EpistemicStatus.INTERPRETIVE)
    assert reading.ceiling is EpistemicStatus.INTERPRETIVE
    assert reading.basis is EpistemicBasis.BOX, "the weaker substrate governs the whole"

    strong_only = tree(strong)
    assert strong_only.ceiling is EpistemicStatus.MEASURED


def test_each_node_keeps_the_basis_of_the_measurement_that_placed_it():
    """The FORM's ceiling weakens with the set; an individual node does not lose its own evidence,
    so a reader can still see which edges are which."""
    weak = relation_artifact([relation("contains", "a", "b", basis="box", status="interpretive",
                                       measurements={"scale_ratio": 0.1})],
                             pairs_examined=1, artifact_id="art_weak", basis="box",
                             status="interpretive")
    reading = tree(fixture("relations.forest.json"), weak)
    by_id = {n.node_id: n for n in reading.payload.nodes}
    assert by_id[key(FOREST, "basin")].basis is EpistemicBasis.MASK
    assert by_id[key(FOREST, "basin")].epistemic_status is EpistemicStatus.MEASURED
    assert by_id[key(FOREST, "a")].basis is EpistemicBasis.BOX


# ── identity, and what a tree may not become ─────────────────────────────────


def test_a_node_is_an_identity_and_never_a_name():
    """Geometric containment is not part/whole, and the absence is structural rather than
    disciplined: there is no field on `ContainmentNode` in which a semantic relationship could be
    recorded, and nothing in this package reads `naming`."""
    reading = tree(fixture("relations.forest.json"))
    as_json = json.loads(reading.payload.model_dump_json())
    assert "label" not in json.dumps(as_json)
    assert "naming" not in json.dumps(as_json)
    for node in reading.payload.nodes:
        assert node.node_id == endpoint_key(node.endpoint)
        assert node.endpoint.artifact_id and node.endpoint.instance_id


def test_the_endpoint_keeps_the_revision_the_relation_cited():
    """`hierarchy_nodes_cite_revisions` is one of this form's declared test obligations. A tree
    over `reg_7` that cannot say which revision of `reg_7` cannot be told it has gone stale."""
    reading = tree(fixture("relations.forest.json"))
    for node in reading.payload.nodes:
        assert node.endpoint.region_id is not None
        assert node.endpoint.geometry_rev == 1


def test_the_payload_survives_the_wire():
    reading = tree(fixture("relations.forest.json"))
    again = TopologyContainmentTreePayload.model_validate(
        json.loads(reading.payload.model_dump_json()))
    assert again == reading.payload


def test_assembling_the_same_relations_twice_gives_the_same_tree():
    """Repeat stability. Ids are derived from what a record is ABOUT, so two runs are comparable
    rather than two sets of uuids that have to be lined up by hand."""
    first = tree(fixture("relations.forest.json"))
    second = tree(fixture("relations.forest.json"))
    assert first.payload.model_dump_json() == second.payload.model_dump_json()
    assert first.implied == second.implied
    assert first.ceiling == second.ceiling


# ════════════════════════════════════════════════════════════════════════════
# the adjacency graph: what touches what, across the whole scene
# ════════════════════════════════════════════════════════════════════════════


def graph(*sets: Dict[str, Any], roster: Optional[Roster] = None,
          loci: Sequence[Any] = (), max_nodes: Optional[int] = None) -> A.AdjacencyReading:
    return A.produce_adjacency_graph(list(sets), roster=roster, loci=loci, max_nodes=max_nodes)


def piers_roster() -> Roster:
    return Roster.of([fixture("extent-set.piers.json")])


def edge_between(reading: A.AdjacencyReading, kind: str, a: str, b: str) -> Any:
    wanted = {key(PIERS, a), key(PIERS, b)}
    found = [e for e in reading.payload.edges
             if e.kind.value == kind and {e.source_node_id, e.target_node_id} == wanted]
    assert len(found) == 1, f"expected one {kind} edge between {a} and {b}, got {len(found)}"
    return found[0]


def test_the_row_of_piers_becomes_one_chain_and_an_island():
    """The nave at Wells, at 40x60. The repeated structure exists only in the assembly."""
    reading = graph(fixture("relations.piers.json"), roster=piers_roster())
    assert reading.producible
    assert [n.node_id for n in reading.payload.nodes] == [
        key(PIERS, i) for i in ("pier_1", "pier_2", "pier_3", "pier_4", "island")]
    assert reading.contact_components == (
        tuple(key(PIERS, i) for i in ("pier_1", "pier_2", "pier_3", "pier_4")),
        (key(PIERS, "island"),))
    assert reading.isolated == (key(PIERS, "island"),)


def test_connectivity_is_asked_of_contact_alone():
    """The graph also records `disjoint` findings, so it is connected under "was compared to".

    Reporting that as connectivity would tell a reader that everything in the scene touches
    everything else — which is the opposite of what ten pairs of measurements found.
    """
    reading = graph(fixture("relations.piers.json"), roster=piers_roster())
    assert any(e.kind is RelationKind.DISJOINT and key(PIERS, "island") in
               (e.source_node_id, e.target_node_id) for e in reading.payload.edges)
    assert reading.isolated == (key(PIERS, "island"),), \
        "the island has four disjoint edges and touches nothing"


def test_an_undirected_relation_is_one_edge_however_it_was_spelled():
    """Adjacency symmetry. `A meets B` and `B meets A` are one finding, and a graph that kept both
    would report a scene twice as densely connected as it was measured to be."""
    both = relation_artifact([relation("meets", "x", "y", directed=False),
                              relation("meets", "y", "x", directed=False)], pairs_examined=1)
    reading = graph(both)
    assert len(reading.payload.edges) == 1
    edge, = reading.payload.edges
    assert (edge.source_node_id, edge.target_node_id) == (key(FOREST, "x"), key(FOREST, "y")), \
        "the pair is recorded in a canonical order, so one finding lands on one edge id"
    assert edge.directed is False
    assert [o.reason for o in reading.omitted] == ["duplicate"]


def test_a_directed_relation_keeps_the_arrow_that_is_its_claim():
    """`nested_within` says which of the two is inside the other. Sorting that pair would lose the
    only thing the measurement found."""
    doc = relation_artifact([relation("nested_within", "z_inner", "a_outer")], pairs_examined=1)
    edge, = graph(doc).payload.edges
    assert edge.directed is True
    assert edge.source_node_id == key(FOREST, "z_inner")
    assert edge.target_node_id == key(FOREST, "a_outer"), \
        "sorted() would have swapped these two and inverted the claim"


def test_two_instances_a_person_called_the_same_thing_stay_two_nodes():
    """`pier_1` and `pier_2` both carry the human label "pier".

    A graph that merged them by name would assert one edge where two were measured, and the
    assertion would be invisible: the merged node would look exactly like a measured one.
    """
    scene = fixture("extent-set.piers.json")
    labels = [i["naming"]["text"] for i in scene["measurement"]["payload"]["instances"]
              if i.get("naming")]
    assert labels == ["pier", "pier"], "the control is only a control if the labels collide"

    reading = graph(fixture("relations.piers.json"), roster=piers_roster())
    assert key(PIERS, "pier_1") in {n.node_id for n in reading.payload.nodes}
    assert key(PIERS, "pier_2") in {n.node_id for n in reading.payload.nodes}
    assert "pier\"" not in json.dumps(json.loads(reading.payload.model_dump_json())), \
        "no label reaches the graph at all"


def test_a_node_id_is_the_key_the_browser_already_builds():
    """Lane E's `relationGraph` keys nodes `${artifact_id}#${instance_id}`.

    Matching it is what makes the browser's DERIVED graph a check against a recorded one rather
    than a second graph sitting beside it.
    """
    reading = graph(fixture("relations.piers.json"), roster=piers_roster())
    for node in reading.payload.nodes:
        assert node.node_id == f"{node.endpoint.artifact_id}#{node.endpoint.instance_id}"


def test_a_declared_member_nothing_touches_is_still_in_the_graph():
    """"Nothing touches it" and "it was never in the set" are different findings, and only a
    declared roster can tell them apart."""
    only_piers = relation_artifact(
        [relation("meets", "pier_1", "pier_2", artifact=PIERS, directed=False)],
        pairs_examined=10)
    with_roster = graph(only_piers, roster=piers_roster())
    assert key(PIERS, "island") in {n.node_id for n in with_roster.payload.nodes}
    assert key(PIERS, "island") in with_roster.isolated

    without = graph(only_piers)
    assert {n.node_id for n in without.payload.nodes} == {key(PIERS, "pier_1"),
                                                          key(PIERS, "pier_2")}
    assert without.bounded_to is None, "no roster is not a bound of zero"


def test_a_bounded_graph_names_every_member_it_left_out():
    """A truncated graph that said nothing about the truncation would read as coverage, which is
    the one thing a scene-wide record must never do."""
    reading = graph(fixture("relations.piers.json"), roster=piers_roster(), max_nodes=3)
    assert len(reading.payload.nodes) == 3
    dropped = {o.what for o in reading.omissions_for("bound_exceeded")}
    assert key(PIERS, "pier_4") in dropped and key(PIERS, "island") in dropped
    assert all(e.source_node_id in {n.node_id for n in reading.payload.nodes}
               for e in reading.payload.edges)
    assert reading.payload.pairs_examined == 10, \
        "ten pairs were still examined; the bound is on the graph, not on the measurement"


def test_an_endpoint_outside_the_roster_is_refused_rather_than_admitted():
    doc = relation_artifact([relation("meets", "pier_1", "ghost", artifact=PIERS, directed=False)],
                            pairs_examined=1)
    reading = graph(doc, roster=piers_roster())
    refusal, = reading.refusals
    assert refusal.code is RefusalCode.UNKNOWN_REFERENCE
    assert reading.payload.edges == []
    assert [o.what for o in reading.omissions_for("endpoint_dangling")] == [key(PIERS, "ghost")]


def test_every_edge_names_two_nodes_the_graph_holds():
    """Lane A refuses a payload whose edge names an unlisted node, so this asserts the producer
    never builds one — including under a bound, which is where it would be easiest to."""
    for reading in (graph(fixture("relations.piers.json"), roster=piers_roster()),
                    graph(fixture("relations.piers.json"), roster=piers_roster(), max_nodes=2),
                    graph(fixture("relations.forest.json"))):
        held = {n.node_id for n in reading.payload.nodes}
        for edge in reading.payload.edges:
            assert {edge.source_node_id, edge.target_node_id} <= held
            assert edge.source_node_id != edge.target_node_id


def test_an_edge_cites_a_recorded_band_and_never_carries_one():
    """A graph able to hold geometry is a graph able to disagree with the measurement it depicts.

    The locus arrives as an `(artifact_id, payload)` pair rather than as an artifact, because
    `topology.contact_locus` is produced by no operation and `PerceptualArtifact` therefore refuses
    to carry one. See `sources.carried`.
    """
    locus_payload = S_locus(key_a=key(PIERS, "pier_1"), key_b=key(PIERS, "pier_2"))
    reading = graph(fixture("relations.piers.json"), roster=piers_roster(),
                    loci=[("art_locus_1", locus_payload)])
    touching = edge_between(reading, "meets", "pier_1", "pier_2")
    assert touching.locus_artifact_id == "art_locus_1"
    assert edge_between(reading, "meets", "pier_2", "pier_3").locus_artifact_id is None

    drawn = json.dumps(json.loads(reading.payload.model_dump_json()))
    assert "mask_rle" not in drawn and "counts" not in drawn


def test_the_edge_keeps_the_numbers_the_relation_measured():
    reading = graph(fixture("relations.piers.json"), roster=piers_roster())
    touching = edge_between(reading, "meets", "pier_1", "pier_2")
    assert touching.measurements["contact_pixels"] > 0
    measured = next(r for r in fixture("relations.piers.json")["measurement"]["payload"]["relations"]
                    if r["kind"] == "meets" and r["source"]["instance_id"] == "pier_1")
    assert touching.measurements == measured["measurements"]


def test_a_box_basis_edge_stays_interpretive_in_the_graph_too():
    doc = relation_artifact([relation("meets", "a", "b", basis="box", status="interpretive",
                                      directed=False)],
                            pairs_examined=1, basis="box", status="interpretive")
    reading = graph(doc)
    edge, = reading.payload.edges
    assert edge.basis is EpistemicBasis.BOX
    assert edge.epistemic_status is EpistemicStatus.INTERPRETIVE
    assert reading.ceiling is EpistemicStatus.INTERPRETIVE


def test_assembling_the_same_scene_twice_gives_the_same_graph():
    first = graph(fixture("relations.piers.json"), roster=piers_roster())
    second = graph(fixture("relations.piers.json"), roster=piers_roster())
    assert first.payload.model_dump_json() == second.payload.model_dump_json()
    assert first.contact_components == second.contact_components


# ════════════════════════════════════════════════════════════════════════════
# the transition: what changed between two revisions of one pair
# ════════════════════════════════════════════════════════════════════════════

REVISION = "art_forms_revision"
ONE_PIXEL = "art_forms_one_pixel"


def transitions(before: str, after: str, **kw: Any) -> X.TransitionReading:
    return X.produce_transition([fixture(before)], [fixture(after)], **kw)


def only_transition(reading: X.TransitionReading) -> Any:
    assert len(reading.payload.transitions) == 1, \
        [t.transition_id for t in reading.payload.transitions]
    return reading.payload.transitions[0]


def test_the_gap_closing_reads_as_disjoint_becoming_meets():
    reading = transitions("relations.revision-0.json", "relations.revision-1.json")
    change = only_transition(reading)
    assert change.before.kind is RelationKind.DISJOINT
    assert change.after.kind is RelationKind.MEETS
    assert change.change is TransitionChange.CHANGED


def test_a_transition_cites_four_revision_pinned_references():
    """`transition_cites_both_revisions` is one of this form's declared test obligations.

    Both endpoints before and both after, and one of the four differs — `bar` was revised and
    `post` was not, which is what makes this a transition rather than a re-measurement.
    """
    change = only_transition(transitions("relations.revision-0.json", "relations.revision-1.json"))
    assert str(change.before.source) == f"{REVISION}#bar@0"
    assert str(change.before.target) == f"{REVISION}#post@0"
    assert str(change.after.source) == f"{REVISION}#bar@1"
    assert str(change.after.target) == f"{REVISION}#post@0"
    assert change.before.source.instance.key == change.after.source.instance.key


def test_the_clearance_and_the_contact_locus_are_recorded_as_the_numbers_that_moved():
    """`TransitionChange` has four words and none of them is "the band moved".

    So the movement is recorded as the measurements it actually consists of, beside the transition
    rather than inside it.
    """
    reading = transitions("relations.revision-0.json", "relations.revision-1.json")
    change = only_transition(reading)
    moved = {d.measurement: (d.before, d.after) for d in reading.deltas_for(change.transition_id)}
    assert moved["clearance_px"] == (3.0, 1.0), "two columns of gap became one pixel of contact"
    assert moved["contact_pixels"] == (0.0, 20.0)
    assert moved["contact_locus_x"][0] is None and moved["contact_locus_x"][1] is not None, \
        "a band that did not exist has no position, and reporting 0 would be a measurement"
    assert all(d.moved for d in reading.deltas)


def test_one_pixel_across_the_threshold_loses_the_nesting_and_not_the_object():
    """THE CONTROL THIS FORM EXISTS FOR. `MIN_CONTAINMENT` is 0.95.

    At revision 0 the inner shape's containment is 90/94 = 0.957447 and it is nested. At revision 1
    the nub is one pixel longer, 90/95 = 0.947368, and it is not. What disappears is the RELATION.
    The instance is the same instance at both revisions, and nothing in this producer mints an
    identity, so there is no mechanism by which a moved pixel could become a new object.
    """
    reading = transitions("relations.one-pixel-0.json", "relations.one-pixel-1.json")
    change = only_transition(reading)
    assert change.change is TransitionChange.DISAPPEARED
    assert change.before.kind is RelationKind.NESTED_WITHIN
    assert change.after.kind is None
    assert change.before.measurements["containment"] == pytest.approx(90 / 94, abs=1e-6)
    assert change.before.source.instance_id == change.after.source.instance_id == "inner"
    assert (change.before.source.geometry_rev, change.after.source.geometry_rev) == (0, 1)
    assert change.before.target.geometry_rev == change.after.target.geometry_rev == 0, \
        "the outer shape was not revised, and the record says so"


def test_a_pair_holding_two_kinds_of_one_family_reports_nothing_for_that_family():
    """The one-pixel control is `meets` AND `overlaps` at both revisions.

    `RelationState` carries one kind, so there is no arrangement of this record that can say so.
    Naming a main one would be this module deciding which measurement counted — and the OTHER
    families still report, which is why the nesting finding above survives.
    """
    reading = transitions("relations.one-pixel-0.json", "relations.one-pixel-1.json")
    ambiguous = reading.omissions_for("ambiguous_state")
    assert ambiguous, "the planarity family holds two kinds at once"
    assert all("planarity" in o.what for o in ambiguous)
    assert all("meets" in o.detail and "overlaps" in o.detail for o in ambiguous)
    assert {t.before.kind for t in reading.payload.transitions} == {RelationKind.NESTED_WITHIN}


def test_a_pair_measured_twice_at_one_revision_is_not_a_transition():
    """Lane A refuses two identical revision pairs outright, so a producer that emitted one could
    not build a payload at all. It is reported as what it is instead."""
    reading = X.produce_transition([fixture("relations.revision-0.json")],
                                   [fixture("relations.revision-0.json")])
    assert reading.payload.transitions == []
    assert [o.reason for o in reading.omissions_for("revision_unchanged")] == ["revision_unchanged"]
    assert reading.unchanged_pairs


def test_an_endpoint_with_no_revision_cannot_be_one_end_of_a_transition():
    """`RelationEndpoint.geometry_rev` is optional — a session-scope relation legitimately carries
    none — so this is a refusal rather than a validation error. The relation is perfectly good and
    it cannot be the subject of a statement about revisions."""
    loose = relation_artifact([relation("meets", "a", "b", directed=False)], pairs_examined=1)
    reading = X.produce_transition([loose], [loose])
    codes = {r.code for r in reading.refusals}
    assert RefusalCode.UNKNOWN_REFERENCE in codes
    assert reading.payload.transitions == []
    assert {o.reason for o in reading.omitted} >= {"revision_missing"}


def test_the_transition_is_deferred_and_says_so_while_still_settling_its_shape():
    """`topology.transition` is registered, designed and unwritable in the merged contract.

    The payload is assembled — that is the whole reason a deferred form is registered a phase
    early — and the verdict travels with it so a caller cannot mint an artifact without stepping
    over a typed no it can see.
    """
    reading = transitions("relations.revision-0.json", "relations.revision-1.json")
    assert reading.producible is False
    assert reading.writable_payload is None
    assert reading.payload is not None
    refusal, = [r for r in reading.refusals if r.code is RefusalCode.FORM_NOT_PRODUCIBLE]
    assert "deferred" in refusal.message
    assert D.form(X.FORM).state == "deferred"


def test_the_count_says_two_states_were_compared():
    """`revisions_compared` is the field that proves something looked. Counting distinct revision
    NUMBERS instead would add revisions of different instances together, which is arithmetic on
    incomparable things."""
    assert transitions("relations.revision-0.json",
                       "relations.revision-1.json").payload.revisions_compared == 2


def test_comparing_the_same_pair_twice_gives_the_same_transition_ids():
    first = transitions("relations.revision-0.json", "relations.revision-1.json")
    second = transitions("relations.revision-0.json", "relations.revision-1.json")
    assert first.payload.model_dump_json() == second.payload.model_dump_json()


# ════════════════════════════════════════════════════════════════════════════
# the conditional set: what would be true, if that reading were right
# ════════════════════════════════════════════════════════════════════════════

CUBIST = "art_forms_cubist"
ONE_OBJECT = "alt_one_object"
TWO_OBJECTS = "alt_two_objects"


def hypothesis_set(*, weights: Tuple[float, float] = (0.62, 0.29)
                   ) -> ExtentHypothesisSetPayload:
    """The two readings of the cubist scene, over ONE extent set.

    Competing readings select different SUBSETS of the same identities — which is what
    `ExtentAlternative.instances` is for, and the only arrangement in which a relation can be found
    to hold under both. Two artifacts would give the same column two node keys.
    """
    def alt(alt_id: str, weight: float, names: Sequence[str]) -> Dict[str, Any]:
        return {"alternative_id": alt_id, "weight": weight, "artifact_id": CUBIST,
                "instances": [{"artifact_id": CUBIST, "instance_id": n} for n in names],
                "grounds": []}
    return ExtentHypothesisSetPayload.model_validate({
        "variant": "extent_hypothesis_set", "alternatives_considered": 2,
        "question": "one form or two, beside the plane?", "weights_are_probabilities": False,
        "alternatives": [alt(ONE_OBJECT, weights[0], ("form", "plane", "column")),
                         alt(TWO_OBJECTS, weights[1],
                             ("form_upper", "form_lower", "plane", "column"))]})


def conditional(readings: Optional[Dict[str, Sequence[Any]]] = None,
                **kw: Any) -> U.HypothesisReading:
    if readings is None:
        readings = {ONE_OBJECT: [fixture("relations.cubist-one.json")],
                    TWO_OBJECTS: [fixture("relations.cubist-two.json")]}
    return U.produce_uncertain_relations(("art_forms_hyp", hypothesis_set()), readings, **kw)


def test_each_hypothesis_is_evaluated_separately_and_keeps_its_own_relations():
    reading = conditional()
    assert reading.evaluated == (ONE_OBJECT, TWO_OBJECTS)
    one = {(r.kind.value, r.source.instance_id, r.target.instance_id)
           for r in reading.relations_for(ONE_OBJECT)}
    two = {(r.kind.value, r.source.instance_id, r.target.instance_id)
           for r in reading.relations_for(TWO_OBJECTS)}
    assert ("overlaps", "form", "plane") in one
    assert ("disjoint", "form_lower", "plane") in two
    assert ("overlaps", "form", "plane") not in two


def test_every_relation_keeps_the_condition_it_hangs_on():
    """`conditional_relation_retains_its_hypothesis`, and Lane A refuses a payload whose condition
    it does not declare. A dropped condition reads exactly like a measurement."""
    reading = conditional()
    declared = {h.hypothesis_id for h in reading.payload.hypotheses}
    assert declared == {ONE_OBJECT, TWO_OBJECTS}
    for relation in reading.payload.relations:
        assert relation.conditioned_on in declared


def test_incompatible_kinds_are_two_relations_and_never_one_average():
    """Under one reading the form overlaps the plane; under the other its lower half stands clear.

    There is no scale on which `overlaps` and `disjoint` are near each other, so there is no scale
    on which to average them — and there is no arithmetic in the producer that could.
    """
    reading = conditional()
    about_the_plane = [r for r in reading.payload.relations
                       if r.target.instance_id == "plane" or r.source.instance_id == "plane"]
    kinds = {(r.conditioned_on, r.kind.value) for r in about_the_plane}
    assert (ONE_OBJECT, "overlaps") in kinds
    assert (TWO_OBJECTS, "disjoint") in kinds
    assert len({r.relation_id for r in about_the_plane}) == len(about_the_plane), \
        "every conditional relation has its own id; nothing was merged"


def test_what_survives_every_reading_is_reported_apart_from_what_does_not():
    """The column stands clear of the plane whichever way the ambiguity resolves. That is a
    different kind of fact from a relation that holds under one reading."""
    reading = conditional()
    assert reading.stable == (f"disjoint|{CUBIST}#column|{CUBIST}#plane",)
    assert f"overlaps|{CUBIST}#form|{CUBIST}#plane" in reading.dependent
    assert f"disjoint|{CUBIST}#form_lower|{CUBIST}#plane" in reading.dependent


def test_a_stable_relation_still_carries_its_condition_in_the_payload():
    """The split is a reading OF the payload, never a part of it.

    A relation that dropped its condition on the grounds of being stable would read exactly like a
    measured one, which is the substitution this form exists to make impossible.
    """
    reading = conditional()
    stable_pairs = [r for r in reading.payload.relations
                    if {r.source.instance_id, r.target.instance_id} == {"column", "plane"}]
    assert {r.conditioned_on for r in stable_pairs} == {ONE_OBJECT, TWO_OBJECTS}
    assert len(stable_pairs) == 2, "one per reading, each naming its own"


def test_no_reading_is_dropped_for_being_unlikely():
    """`a_hypothesis_is_not_curated_by_confidence`. The low-weight reading is the one a person most
    needs to see before they choose."""
    faint = U.produce_uncertain_relations(
        ("art_forms_hyp", hypothesis_set(weights=(0.99, 0.01))),
        {ONE_OBJECT: [fixture("relations.cubist-one.json")],
         TWO_OBJECTS: [fixture("relations.cubist-two.json")]})
    weights = {h.hypothesis_id: h.weight for h in faint.payload.hypotheses}
    assert weights == {ONE_OBJECT: 0.99, TWO_OBJECTS: 0.01}
    assert faint.relations_for(TWO_OBJECTS), "the unlikely reading was evaluated and kept"


def test_an_alternative_nothing_was_measured_under_is_still_declared():
    """It was considered. Dropping the citation would shrink the space of readings a later person
    can see was open — and that is a silent resolution of the ambiguity."""
    reading = conditional({ONE_OBJECT: [fixture("relations.cubist-one.json")]})
    assert reading.unevaluated == (TWO_OBJECTS,)
    assert {h.hypothesis_id for h in reading.payload.hypotheses} == {ONE_OBJECT, TWO_OBJECTS}
    assert reading.relations_for(TWO_OBJECTS) == ()
    assert reading.stable and not reading.dependent, \
        "one evaluated reading contradicts nothing, so everything it found stands under it"


def test_relations_supplied_under_an_undeclared_reading_are_refused():
    """A condition nobody can look up is a condition that has been dropped."""
    reading = conditional({ONE_OBJECT: [fixture("relations.cubist-one.json")],
                           "alt_invented": [fixture("relations.cubist-two.json")]})
    refusal, = [r for r in reading.refusals if "alt_invented" in r.message]
    assert refusal.code is RefusalCode.UNKNOWN_REFERENCE
    assert all(r.conditioned_on != "alt_invented" for r in reading.payload.relations)


def test_a_conditional_relation_is_never_measured_however_it_was_computed():
    """The masks were measured. The relation between things that may not be those things was not.

    Both ceilings apply: the basis's, and the partition's. `unresolved_alternative` caps at
    `uncertain` independently of a perfect mask basis, and no confidence lifts it.
    """
    reading = conditional()
    source = fixture("relations.cubist-one.json")["measurement"]["payload"]["relations"]
    assert {r["epistemic_status"] for r in source} == {"measured"}, \
        "the relations underneath were measured; the control is only a control if they were"
    for relation in reading.payload.relations:
        assert relation.epistemic_status not in (EpistemicStatus.MEASURED, EpistemicStatus.VISIBLE)
        assert STATUS_ORDER[relation.epistemic_status] <= STATUS_ORDER[U.CONDITIONAL_CEILING]
    assert reading.ceiling is EpistemicStatus.UNCERTAIN
    assert PARTITION_CEILINGS[EpistemicPartition.UNRESOLVED_ALTERNATIVE] is EpistemicStatus.UNCERTAIN


def test_the_conditional_set_is_deferred_and_says_so():
    reading = conditional()
    assert reading.producible is False
    assert reading.writable_payload is None
    assert any(r.code is RefusalCode.FORM_NOT_PRODUCIBLE for r in reading.refusals)
    assert D.form(U.FORM).state == "deferred"


def test_assembling_the_same_readings_twice_gives_the_same_conditional_set():
    assert conditional().payload.model_dump_json() == conditional().payload.model_dump_json()
