"""
PERCEPTUAL-FORMS-001D — what the structural Topology forms are allowed to say.

Organised by the CLAIMS these producers have to earn, not by the functions they happen to have.
The deliverable is not "four producers run"; it is that a person reading a tree, a graph, a
transition or a conditional set can believe what it says AND can see what it left out:

    direction      a nesting means the same thing in both spellings, and the tree is the same tree
    reduction      a redundant ancestor is ABSORBED by transitivity, never deleted
    disagreement   cycles and incomparable parents are reported, never broken or chosen between
    identity       a node is `artifact_id#instance_id`. A label never merges two of them, and a
                   revision never mints a third
    bounds         a declared member with no edges stays visible; an undeclared endpoint is refused
    revision       a transition cites four pinned references, and a threshold crossing is a change
                   in the RELATION and not in the object
    hypotheses     every conditional relation keeps its condition, no kind is ever averaged, and
                   no reading is dropped for being unlikely
    ceilings       box basis stays interpretive; a composition never outruns its weakest input
    isolation      no Extent call, no Depth call, no database, no post — proved on the import
                   closure rather than promised in a docstring

THE CONTROLS ARE SYNTHETIC AND COMMITTED, generated by
`scripts/perception_lab_topology_form_fixtures.py`: rectangles on a 40x60 raster whose structure is
known before the organ runs, each written twice — as the `extent_set` a topology operation consumes
and as the `topology_relation_set` the façade measured from it. The suite runs the generator's
`--check` by name, so a scene edited and not regenerated fails here rather than drifting quietly.

The mutation tests at the end are the other half. Each deletes one guard and asserts the deletion
turns a named test red — a law nothing fails on is a comment.
"""
from __future__ import annotations

import ast
import copy
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import pytest

from backend.schemas.perception_lab import (BASIS_CEILINGS, STATUS_ORDER, EpistemicBasis,
                                            EpistemicStatus, PerceptualArtifact, RefusalCode,
                                            RelationKind, TopologyContainmentTreePayload)
from backend.services.perception_lab import definitions as D
from backend.services.perception_lab.topology_forms import containment as C
from backend.services.perception_lab.topology_forms.sources import Roster, endpoint_key

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_DIR = REPO_ROOT / "research" / "perception_lab" / "fixtures" / "topology_forms"
FIXTURE_SCRIPT = REPO_ROOT / "scripts" / "perception_lab_topology_form_fixtures.py"


def fixture(name: str) -> Dict[str, Any]:
    return json.loads((FIXTURE_DIR / name).read_text(encoding="utf-8"))


def key(artifact: str, instance: str) -> str:
    return f"{artifact}#{instance}"


FOREST = "art_forms_forest"
PIERS = "art_forms_piers"
AMBIGUOUS = "art_forms_ambiguous"


# ── building relation sets by hand, for the cases geometry cannot produce ────


def relation(kind: str, source: str, target: str, *, artifact: str = FOREST,
             relation_id: Optional[str] = None, basis: str = "mask",
             status: str = "measured", directed: bool = True,
             measurements: Optional[Dict[str, float]] = None,
             source_artifact: Optional[str] = None,
             target_artifact: Optional[str] = None) -> Dict[str, Any]:
    """One relation, as JSON. Used where a real scene cannot make the case.

    A CONTAINMENT CYCLE IS THE MOTIVATING EXAMPLE, and it is worth saying why it must be
    hand-written. `nestedness_organ` will not report A inside B and B inside A off one raster —
    `MAX_SCALE_RATIO` forbids it. A cycle in the wild arrives the other way: two measurements taken
    at different revisions, on different bases, or in different runs, composed afterwards. Which is
    exactly what these producers do, and exactly why they have to survive it.
    """
    return {
        "relation_id": relation_id or f"rel_{kind}_{source}_{target}",
        "kind": kind,
        "source": {"artifact_id": source_artifact or artifact, "instance_id": source,
                   "scope": "session", "region_id": None, "geometry_rev": None},
        "target": {"artifact_id": target_artifact or artifact, "instance_id": target,
                   "scope": "session", "region_id": None, "geometry_rev": None},
        "directed": directed, "basis": basis, "epistemic_status": status,
        "measurements": measurements or {}, "stale": False,
    }


def relation_artifact(relations: Sequence[Dict[str, Any]], *, pairs_examined: int,
                      artifact_id: str = "art_hand_relations", basis: str = "mask",
                      status: str = "measured") -> Dict[str, Any]:
    """A contract-shaped `topology.pair_relation` artifact around hand-written relations.

    Built by replacing the payload of a generated control rather than typed out, so that a change
    to the artifact envelope shows up in one place instead of in every hand-made case.
    """
    doc = copy.deepcopy(fixture("relations.forest.json"))
    doc["identity"]["artifact_id"] = artifact_id
    doc["identity"]["identity_refs"] = []
    doc["measurement"]["payload"] = {"variant": "topology_relation_set",
                                     "pairs_examined": pairs_examined,
                                     "relations": list(relations), "bounded_to": None}
    doc["measurement"]["epistemic_basis"] = basis
    doc["measurement"]["epistemic_status"] = status
    return PerceptualArtifact.model_validate(doc).model_dump(mode="json")


def inverted(doc: Dict[str, Any]) -> Dict[str, Any]:
    """The same relation set, every nesting spelled from the other end.

    `contains(A→B)` and `nested_within(B→A)` are one measurement read from two sides. This swaps
    the spelling without touching the measurement, which is what lets the direction law be tested
    as an EQUIVALENCE rather than as two separate assertions that happen to agree.
    """
    out = copy.deepcopy(doc)
    flip = {"contains": "nested_within", "nested_within": "contains"}
    for rel in out["measurement"]["payload"]["relations"]:
        if rel["kind"] in flip:
            rel["kind"] = flip[rel["kind"]]
            rel["source"], rel["target"] = rel["target"], rel["source"]
    return out


def tree(*sets: Dict[str, Any], roster: Optional[Roster] = None) -> C.ContainmentReading:
    return C.produce_containment_tree(list(sets), roster=roster)


def parents(reading: C.ContainmentReading) -> Dict[str, Optional[str]]:
    return {n.node_id: n.parent_node_id for n in reading.payload.nodes}


# ── the controls are the controls ────────────────────────────────────────────


def test_the_committed_controls_are_what_the_generator_builds():
    """`--check` by name, so a scene edited and not regenerated fails here.

    It is also a drift alarm on `topology.py`: the relation sets are what the real façade measured
    from the real scenes, so a change in how a relation is recorded reaches this suite as a diff a
    person reads rather than as a silent change in what the composition was tested against.
    """
    done = subprocess.run([sys.executable, str(FIXTURE_SCRIPT), "--check"],
                          capture_output=True, text=True, cwd=str(REPO_ROOT))
    assert done.returncode == 0, done.stderr


def test_every_control_is_a_contract_valid_artifact():
    for path in sorted(FIXTURE_DIR.glob("*.json")):
        again = PerceptualArtifact.model_validate(json.loads(path.read_text(encoding="utf-8")))
        assert again.identity.organ_family.value in ("extent", "topology")


# ── the forest: what nesting composes into ───────────────────────────────────


def test_the_nested_forest_composes_into_two_roots_and_three_levels():
    reading = tree(fixture("relations.forest.json"))
    assert reading.producible, "containment_tree is `experimental`, not deferred"
    assert set(reading.payload.root_node_ids) == {key(FOREST, "court"), key(FOREST, "wall")}
    assert parents(reading) == {
        key(FOREST, "court"): None,
        key(FOREST, "fountain"): key(FOREST, "court"),
        key(FOREST, "basin"): key(FOREST, "fountain"),
        key(FOREST, "wall"): None,
        key(FOREST, "niche"): key(FOREST, "wall"),
    }


def test_the_occupancy_is_quoted_from_the_measurement_and_never_recomputed():
    """`scale_ratio` is `area(inner) / area(outer)`, measured by `nestedness_organ`.

    The basin is 4x4 in a 12x10 fountain: 16/120. A producer that recomputed it from areas would
    be making a measurement, and this lane does not make measurements.
    """
    reading = tree(fixture("relations.forest.json"))
    by_id = {n.node_id: n for n in reading.payload.nodes}
    assert by_id[key(FOREST, "basin")].occupancy_of_parent == pytest.approx(16 / 120, abs=1e-6)
    assert by_id[key(FOREST, "fountain")].occupancy_of_parent == pytest.approx(120 / 1064,
                                                                              abs=1e-6)
    for root in reading.payload.root_node_ids:
        assert by_id[root].occupancy_of_parent is None, "a root occupies no parent"


def test_a_nesting_means_the_same_thing_spelled_from_either_end():
    """The direction law, as an equivalence. `contains(A→B)` and `nested_within(B→A)` are one
    measurement, so the two spellings must build one tree."""
    forward = tree(fixture("relations.forest.json"))
    backward = tree(inverted(fixture("relations.forest.json")))
    assert parents(forward) == parents(backward)
    assert forward.payload.root_node_ids == backward.payload.root_node_ids


def test_the_redundant_ancestor_is_absorbed_by_transitivity_and_not_deleted():
    """`court ⊃ basin` was measured AND is implied by `court ⊃ fountain ⊃ basin`.

    The tree holds the NEARER holder, and the reader still reads basin inside court by walking. The
    absorbed relation is named, because "this edge is redundant" and "this edge was dropped" look
    identical from outside and only one of them is true.
    """
    reading = tree(fixture("relations.forest.json"))
    absorbed = [r for r in fixture("relations.forest.json")["measurement"]["payload"]["relations"]
                if r["kind"] == "contains" and r["source"]["instance_id"] == "court"
                and r["target"]["instance_id"] == "basin"]
    assert len(absorbed) == 1
    assert reading.implied == (absorbed[0]["relation_id"],)
    assert not reading.omissions_for("containment_conflict")

    walk, node = [], key(FOREST, "basin")
    by_id = {n.node_id: n for n in reading.payload.nodes}
    while node is not None:
        walk.append(node)
        node = by_id[node].parent_node_id
    assert walk == [key(FOREST, "basin"), key(FOREST, "fountain"), key(FOREST, "court")]


def test_pairs_examined_is_carried_through_rather_than_recounted():
    """Ten pairs were compared for the forest. A composition that recounted from the relations it
    received would report a number about itself, and `pairs_examined` is the field that separates a
    measured emptiness from an absence of measurement."""
    reading = tree(fixture("relations.forest.json"))
    assert reading.payload.pairs_examined == 10

    nothing = tree(relation_artifact([], pairs_examined=6))
    assert nothing.payload.pairs_examined == 6, "six pairs were compared and nothing nested"
    assert nothing.payload.nodes == []


# ── disagreement: never broken, never chosen between ─────────────────────────


def test_two_incomparable_holders_exclude_the_node_and_name_both():
    """One shape inside two overlapping shapes that contain neither.

    `ContainmentNode` holds ONE parent, so there is no arrangement of this record that can say
    where `inner` is. Both candidates are named in a conflict and the node leaves.
    """
    reading = tree(fixture("relations.ambiguous.json"))
    inner = key(AMBIGUOUS, "inner")
    assert inner not in parents(reading)
    conflict, = [c for c in reading.conflicts if c.kind == "ambiguous_parents"]
    assert conflict.node_key == inner
    assert conflict.candidates == (key(AMBIGUOUS, "left_hall"), key(AMBIGUOUS, "right_hall"))
    assert len(conflict.relation_ids) == 2
    assert [o.what for o in reading.omissions_for("containment_conflict")] == [inner]


def test_a_disputed_node_is_never_parked_at_the_root():
    """The tempting move, and the one that would turn an ambiguity into a finding.

    `root_node_ids` means "nothing holds it". A node whose holders are in dispute is held by two
    things, and listing it as a root would report top-level-ness that two measurements contradict.
    """
    reading = tree(fixture("relations.ambiguous.json"))
    assert key(AMBIGUOUS, "inner") not in reading.payload.root_node_ids
    assert set(reading.payload.root_node_ids) == {key(AMBIGUOUS, "left_hall"),
                                                 key(AMBIGUOUS, "right_hall")}


def test_a_containment_cycle_is_reported_and_never_broken():
    """A ⊂ B ⊂ A means two measurements disagree. Breaking it would hide the disagreement, and
    Lane A's `_acyclic` will not validate a payload that contains one."""
    doc = relation_artifact([relation("contains", "a", "b"), relation("contains", "b", "a")],
                            pairs_examined=1)
    reading = tree(doc)
    assert reading.payload.nodes == [], "neither end of a contradiction may stand in the tree"
    cycled = {c.node_key for c in reading.conflicts if c.kind == "cycle"}
    assert cycled == {key(FOREST, "a"), key(FOREST, "b")}, "the whole cycle, not an entry point"
    assert {o.what for o in reading.omissions_for("containment_cycle")} == cycled


def test_a_longer_cycle_names_every_node_on_it():
    doc = relation_artifact([relation("contains", "a", "b"), relation("contains", "b", "c"),
                             relation("contains", "c", "a")], pairs_examined=3)
    reading = tree(doc)
    assert {c.node_key for c in reading.conflicts if c.kind == "cycle"} == {
        key(FOREST, "a"), key(FOREST, "b"), key(FOREST, "c")}


def test_excluding_a_node_excludes_what_hung_from_it():
    """The cascade. `deep` is inside `inner`, whose holders are in dispute.

    Leaving `deep` behind pointing at a node the record no longer holds would not validate, and
    re-rooting it would claim a top-level-ness the relations contradict just as loudly as the
    dispute they contradict.
    """
    doc = relation_artifact([relation("contains", "left", "inner"),
                             relation("contains", "right", "inner"),
                             relation("contains", "inner", "deep")], pairs_examined=3)
    reading = tree(doc)
    held = set(parents(reading))
    assert key(FOREST, "inner") not in held
    assert key(FOREST, "deep") not in held
    assert [o.what for o in reading.omissions_for("orphaned_by_exclusion")] == [key(FOREST, "deep")]
    assert set(reading.payload.root_node_ids) == {key(FOREST, "left"), key(FOREST, "right")}


def test_a_node_held_only_by_a_cycle_leaves_with_it():
    doc = relation_artifact([relation("contains", "a", "b"), relation("contains", "b", "a"),
                             relation("contains", "b", "child")], pairs_examined=3)
    reading = tree(doc)
    assert parents(reading) == {}, "nothing here is held by anything the record can stand behind"
    assert [o.what for o in reading.omissions_for("orphaned_by_exclusion")] == [
        key(FOREST, "child")]


# ── bounds, and endpoints that are not there ─────────────────────────────────


def test_a_relation_citing_an_endpoint_outside_the_roster_is_refused():
    """A roster is the caller's declaration of what this structure may hold, read off the extent
    artifacts they supplied. A nesting over an endpoint nobody supplied would be a structure about
    something this record cannot show."""
    roster = Roster.of([fixture("extent-set.forest.json")])
    doc = relation_artifact([relation("contains", "court", "ghost")], pairs_examined=1)
    reading = tree(doc, roster=roster)
    refusal, = reading.refusals
    assert refusal.code is RefusalCode.UNKNOWN_REFERENCE
    assert key(FOREST, "ghost") in refusal.message
    assert [o.what for o in reading.omissions_for("endpoint_dangling")] == [key(FOREST, "ghost")]
    assert reading.payload.nodes == [], "the relation contributed no edge"


def test_without_a_roster_nothing_can_dangle_and_that_is_not_the_same_as_admitting_it():
    """Absent a declared bound, a structure is over exactly what its relations cite. There is no
    roster to fall outside of, so there is no dangling reference — and the two situations are told
    apart by whether a roster was given, never by a default."""
    doc = relation_artifact([relation("contains", "court", "ghost")], pairs_examined=1)
    reading = tree(doc)
    assert reading.refusals == ()
    assert set(parents(reading)) == {key(FOREST, "court"), key(FOREST, "ghost")}


def test_a_shape_inside_itself_is_not_a_level_of_a_nesting():
    doc = relation_artifact([relation("contains", "a", "a")], pairs_examined=1)
    reading = tree(doc)
    assert reading.payload.nodes == []
    assert [o.reason for o in reading.omitted] == ["self_pair"]


def test_relations_that_are_not_nestings_are_named_rather_than_ignored():
    """The forest control carries `overlaps` and `disjoint` too. A producer that silently skipped
    them would report the same tree as one that had never been handed them."""
    reading = tree(fixture("relations.forest.json"))
    skipped = reading.omissions_for("not_a_structural_kind")
    assert len(skipped) == 10, "four overlaps and six disjoints"
    assert all("is not a nesting" in o.detail for o in skipped)


# ── the ceilings a composition may not climb ─────────────────────────────────


def test_a_box_basis_nesting_stays_interpretive_however_confident_it_is():
    doc = relation_artifact([relation("contains", "outer", "inner", basis="box",
                                      status="interpretive",
                                      measurements={"scale_ratio": 0.02, "containment": 0.999})],
                            pairs_examined=1, basis="box", status="interpretive")
    reading = tree(doc)
    node = next(n for n in reading.payload.nodes if n.parent_node_id is not None)
    assert node.basis is EpistemicBasis.BOX
    assert node.epistemic_status is EpistemicStatus.INTERPRETIVE
    assert reading.ceiling is EpistemicStatus.INTERPRETIVE
    assert BASIS_CEILINGS[EpistemicBasis.BOX] is EpistemicStatus.INTERPRETIVE


def test_a_composition_never_outruns_the_weakest_artifact_under_it():
    """`exact_derivation` is capped by its inputs, and that cap needs the inputs in hand — which is
    why it is asked of `derived_ceiling` and recorded on the production rather than left to a
    validator looking at one record."""
    weak = relation_artifact([relation("contains", "a", "b", basis="box", status="interpretive",
                                       measurements={"scale_ratio": 0.1})],
                             pairs_examined=1, artifact_id="art_weak", basis="box",
                             status="interpretive")
    strong = fixture("relations.forest.json")
    reading = tree(strong, weak)
    assert reading.input_statuses == (EpistemicStatus.MEASURED, EpistemicStatus.INTERPRETIVE)
    assert reading.ceiling is EpistemicStatus.INTERPRETIVE
    assert reading.basis is EpistemicBasis.BOX, "the weaker substrate governs the whole"

    strong_only = tree(strong)
    assert strong_only.ceiling is EpistemicStatus.MEASURED


def test_each_node_keeps_the_basis_of_the_measurement_that_placed_it():
    """The FORM's ceiling weakens with the set; an individual node does not lose its own evidence,
    so a reader can still see which edges are which."""
    weak = relation_artifact([relation("contains", "a", "b", basis="box", status="interpretive",
                                       measurements={"scale_ratio": 0.1})],
                             pairs_examined=1, artifact_id="art_weak", basis="box",
                             status="interpretive")
    reading = tree(fixture("relations.forest.json"), weak)
    by_id = {n.node_id: n for n in reading.payload.nodes}
    assert by_id[key(FOREST, "basin")].basis is EpistemicBasis.MASK
    assert by_id[key(FOREST, "basin")].epistemic_status is EpistemicStatus.MEASURED
    assert by_id[key(FOREST, "a")].basis is EpistemicBasis.BOX


# ── identity, and what a tree may not become ─────────────────────────────────


def test_a_node_is_an_identity_and_never_a_name():
    """Geometric containment is not part/whole, and the absence is structural rather than
    disciplined: there is no field on `ContainmentNode` in which a semantic relationship could be
    recorded, and nothing in this package reads `naming`."""
    reading = tree(fixture("relations.forest.json"))
    as_json = json.loads(reading.payload.model_dump_json())
    assert "label" not in json.dumps(as_json)
    assert "naming" not in json.dumps(as_json)
    for node in reading.payload.nodes:
        assert node.node_id == endpoint_key(node.endpoint)
        assert node.endpoint.artifact_id and node.endpoint.instance_id


def test_the_endpoint_keeps_the_revision_the_relation_cited():
    """`hierarchy_nodes_cite_revisions` is one of this form's declared test obligations. A tree
    over `reg_7` that cannot say which revision of `reg_7` cannot be told it has gone stale."""
    reading = tree(fixture("relations.forest.json"))
    for node in reading.payload.nodes:
        assert node.endpoint.region_id is not None
        assert node.endpoint.geometry_rev == 1


def test_the_payload_survives_the_wire():
    reading = tree(fixture("relations.forest.json"))
    again = TopologyContainmentTreePayload.model_validate(
        json.loads(reading.payload.model_dump_json()))
    assert again == reading.payload


def test_assembling_the_same_relations_twice_gives_the_same_tree():
    """Repeat stability. Ids are derived from what a record is ABOUT, so two runs are comparable
    rather than two sets of uuids that have to be lined up by hand."""
    first = tree(fixture("relations.forest.json"))
    second = tree(fixture("relations.forest.json"))
    assert first.payload.model_dump_json() == second.payload.model_dump_json()
    assert first.implied == second.implied
    assert first.ceiling == second.ceiling
