/**
 * SOCIETY — a MeetingView fixture, so the surface's honesty rules are testable with no backend.
 *
 * Contains one of each outcome on purpose: a COMPOSED pair with a proposed joint hypothesis, a
 * COEXISTENT pair, an INCOMMENSURABLE pair, and a wholly-received REFUSAL. A fixture missing any
 * of them would let the surface pass while unable to render the case it exists for.
 */
export const meetingFixture = {
    node_id: 'vm_pMeet:rim',
    convened: true,
    detail: '3 agents at vm_pMeet:rim: 1 composed, 1 coexistent, 1 incommensurable',
    members: [
        { id: 'agent_nestedness', organ_set: ['nestedness_organ'], measured: 2, arities: [2] },
        { id: 'agent_adjacency', organ_set: ['adjacency_organ'], measured: 3, arities: [2] },
        { id: 'agent_chroma', organ_set: ['chroma_organ'], measured: 1, arities: [1] },
    ],
    classes: [['agent_adjacency', 'agent_nestedness'], ['agent_chroma']],
    silent: [],
    outcomes: { composed: 1, coexistent: 1, incommensurable: 1 },
    verdicts: [
        { left: 'agent_nestedness', right: 'agent_adjacency', outcome: 'composed',
          detail: '1 claim(s) neither made alone, over 1 shared subject(s)',
          shared_subjects: ['whole'], hypotheses: ['ahyp_1'] },
        { left: 'agent_nestedness', right: 'agent_chroma', outcome: 'incommensurable',
          detail: 'a warmth mean and a nesting index are both small floats, and that is a fact about floating point rather than about the picture. There is no common scale.',
          shared_subjects: [], hypotheses: [] },
        { left: 'agent_adjacency', right: 'agent_chroma', outcome: 'coexistent',
          detail: 'can be about the same things and are not: 0 shared subject(s)',
          shared_subjects: [], hypotheses: [] },
    ],
    hypotheses: [{
        hypothesis_id: 'ahyp_1',
        claim: 'nested_at_boundary',
        agent_ids: ['agent_nestedness', 'agent_adjacency'],
        about_region_id: 'whole',
        ledger_status: 'proposed',
        marks_live: '0/2',
        detail_ledger: 'a joint hypothesis is a composition over two measurements, not a measurement.',
        rests_on: [
            { agent_id: 'agent_nestedness', organ: 'nestedness_organ', mark_id: 'vm_nest_1',
              relation: 'nested_within', basis: 'mask', detail: 'containment 0.99',
              live: false, epistemic: null },
            { agent_id: 'agent_adjacency', organ: 'adjacency_organ', mark_id: 'vm_adj_1',
              relation: 'meets', basis: 'mask', detail: 'contact 0.60',
              live: false, epistemic: null },
        ],
    }],
    held: {
        agent_nestedness: [{ agent_id: 'agent_nestedness', hypothesis_id: 'ahyp_1',
                             claim: 'nested_at_boundary', epistemic_status: 'interpretive',
                             contributed: 1, received: 1 }],
        agent_adjacency: [{ agent_id: 'agent_adjacency', hypothesis_id: 'ahyp_1',
                            claim: 'nested_at_boundary', epistemic_status: 'interpretive',
                            contributed: 1, received: 1 }],
        agent_chroma: [],
    },
    refusals_to_hold: [{
        agent_id: 'agent_chroma', hypothesis_id: 'ahyp_1', claim: 'nested_at_boundary',
        reason: 'wholly_received',
        detail: 'agent_chroma contributed no mark to this claim — it was in the room when it was made.',
    }],
    journeys: {},
    // The full walks, in the cognition view's own shape — the route already computed these and
    // (until WAVE4 · journeys) threw them away. One of the three ends with every road refused, so
    // the surface's refusal rendering is exercised at the group scale rather than assumed.
    walks: {
        agent_nestedness: {
            agent_id: 'agent_nestedness', temperament: 'analogy_seeker',
            character: { name: 'analogy_seeker', prefers: ['axis_nestedness'],
                         detail: 'moves between pictures before moving through one' },
            organ_set: ['nestedness_organ'],
            first_signature: [['nestedness_organ', 'nested_within', 'within', 'whole', 'mask', 'measured']],
            stations: [{
                index: 0, node_id: 'vm_pA:part', post_id: 'pA', region_id: 'part',
                perceptions: [{ organ: 'nestedness_organ', relation: 'nested_within',
                                direction: 'within', other_region_id: 'whole', basis: 'mask',
                                admissible: true, epistemic: 'measured',
                                expression: 'part nested within whole',
                                detail: 'mask containment 0.99', mark_id: 'vm_nest_1' }],
                horizon: { reachable: [], refused: [], tally: { reachable: 1, refused_edge: 0, refused_traveller: 0 } },
                signature: [],
            }, {
                index: 1, node_id: 'vm_pMeet:rim', post_id: 'pMeet', region_id: 'rim',
                perceptions: [{ organ: 'nestedness_organ', relation: 'nested_within',
                                direction: 'within', other_region_id: 'whole', basis: 'mask',
                                admissible: true, epistemic: 'measured',
                                expression: 'rim nested within whole',
                                detail: 'mask containment 0.98', mark_id: 'vm_nest_2' }],
                horizon: { reachable: [], refused: [], tally: { reachable: 0, refused_edge: 0, refused_traveller: 0 } },
                signature: [],
            }],
            steps: [{ from_node: 'vm_pA:part', to_node: 'vm_pMeet:rim', crossed_image: true,
                      kind: 'between pictures', axis_ref: 'axis_nestedness',
                      relation: 'nested_within', mark_id: 'vm_nest_1', basis: 'mask',
                      epistemic: 'measured', ledger_status: 'proposed', systematicity: 0.72,
                      policy: 'strongest_systematicity', rule: 'take the strongest crossing',
                      arrived_with: 0,
                      arrival_detail: 'arrived with an empty field — everything it knew was knowledge from where it stood',
                      detail: 'an analogy step' }],
            proposals: [],
            tally: { stations: 2, steps: 1, within_one_picture: 0, between_pictures: 1,
                     perceived: 2, refused: 0, proposed: 0 },
        },
        agent_adjacency: {
            agent_id: 'agent_adjacency', temperament: 'contact_seeker',
            character: { name: 'contact_seeker', prefers: ['axis_adjacency'],
                         detail: 'follows what touches what' },
            organ_set: ['adjacency_organ'],
            first_signature: [],
            stations: [{
                index: 0, node_id: 'vm_pB:edge', post_id: 'pB', region_id: 'edge',
                perceptions: [{ organ: 'adjacency_organ', relation: 'meets', direction: 'meets',
                                other_region_id: 'whole', basis: 'mask', admissible: true,
                                epistemic: 'measured', expression: 'edge meets whole',
                                detail: 'contact 0.60 over 44 px', mark_id: 'vm_adj_1' }],
                horizon: {
                    reachable: [],
                    refused: [{ to_node: 'vm_pZ:far', reason: 'interpretive_basis', about: 'edge',
                                gloss: 'it is grounded on an estimate, not a measurement',
                                axis_ref: 'axis_adjacency', relation: 'meets', basis: 'box',
                                detail: 'the mark is box-basis' }],
                    tally: { reachable: 1, refused_edge: 1, refused_traveller: 0 },
                },
                signature: [],
            }, {
                index: 1, node_id: 'vm_pMeet:rim', post_id: 'pMeet', region_id: 'rim',
                perceptions: [{ organ: 'adjacency_organ', relation: 'meets', direction: 'meets',
                                other_region_id: 'whole', basis: 'mask', admissible: true,
                                epistemic: 'measured', expression: 'rim meets whole',
                                detail: 'contact 0.60 over 44 px', mark_id: 'vm_adj_2' }],
                horizon: { reachable: [], refused: [], tally: { reachable: 0, refused_edge: 0, refused_traveller: 0 } },
                signature: [],
            }],
            steps: [{ from_node: 'vm_pB:edge', to_node: 'vm_pMeet:rim', crossed_image: true,
                      kind: 'between pictures', axis_ref: 'axis_adjacency', relation: 'meets',
                      mark_id: 'vm_adj_1', basis: 'mask', epistemic: 'measured',
                      ledger_status: 'proposed', systematicity: 0.65,
                      policy: 'strongest_systematicity', rule: 'take the strongest crossing',
                      arrived_with: 0,
                      arrival_detail: 'arrived with an empty field — everything it knew was knowledge from where it stood',
                      detail: 'a contact step' }],
            proposals: [],
            tally: { stations: 2, steps: 1, within_one_picture: 0, between_pictures: 1,
                     perceived: 2, refused: 1, proposed: 0 },
        },
        agent_chroma: {
            agent_id: 'agent_chroma', temperament: 'depth_seeker',
            character: { name: 'depth_seeker', prefers: ['axis_occlusion'],
                         detail: 'moves through a scene before moving between pictures' },
            organ_set: ['chroma_organ'],
            first_signature: [],
            stations: [{
                index: 0, node_id: 'vm_pC:wall', post_id: 'pC', region_id: 'wall',
                perceptions: [{ organ: 'chroma_organ', relation: 'warmth_field', direction: 'field',
                                other_region_id: null, basis: 'mask', admissible: true,
                                epistemic: 'measured',
                                expression: 'wall reads +0.308 on the warm/cool axis',
                                detail: 'mask warmth +0.308', mark_id: 'vm_chr_1' }],
                horizon: { reachable: [], refused: [], tally: { reachable: 1, refused_edge: 0, refused_traveller: 0 } },
                signature: [],
            }, {
                index: 1, node_id: 'vm_pMeet:rim', post_id: 'pMeet', region_id: 'rim',
                perceptions: [{ organ: 'chroma_organ', relation: 'warmth_field', direction: 'field',
                                other_region_id: null, basis: 'mask', admissible: true,
                                epistemic: 'measured',
                                expression: 'rim reads +0.114 on the warm/cool axis',
                                detail: 'mask warmth +0.114', mark_id: 'vm_chr_2' }],
                horizon: {
                    reachable: [],
                    refused: [{ to_node: 'vm_pD:sky', reason: 'box_footing', about: 'traveller',
                                gloss: "the agent's own footing is a box — an estimate cannot carry a crossing",
                                axis_ref: 'axis_nestedness', relation: null, basis: null,
                                detail: 'the agent stands on an estimate' }],
                    tally: { reachable: 0, refused_edge: 0, refused_traveller: 1 },
                },
                signature: [],
                ended: { reason: 'no reachable crossing from here', available: [] },
            }],
            steps: [{ from_node: 'vm_pC:wall', to_node: 'vm_pMeet:rim', crossed_image: true,
                      kind: 'between pictures', axis_ref: 'axis_nestedness',
                      relation: 'nested_within', mark_id: 'vm_nest_9', basis: 'mask',
                      epistemic: 'measured', ledger_status: 'proposed', systematicity: 0.58,
                      policy: 'strongest_systematicity', rule: 'take the strongest crossing',
                      arrived_with: 0,
                      arrival_detail: 'arrived with an empty field — everything it knew was knowledge from where it stood',
                      detail: 'fell back to an analogy step' }],
            proposals: [],
            tally: { stations: 2, steps: 1, within_one_picture: 0, between_pictures: 1,
                     perceived: 2, refused: 1, proposed: 0 },
        },
    },
};

export default meetingFixture;
