"""
CIRCUIT-002 SURFACE-002 — `runViewFixture`: the one shape both lanes build against.

Lane A (backend) asserts that a real run serialises to this shape. Lane B (the demo frontend)
renders from it while Lane A's routes are still being written, then swaps the mock for the live
endpoint without a rewrite. That only works if the fixture cannot quietly drift from the code, so
there are two halves here and a test that ties them together:

    RUN_VIEW_FIXTURE   the committed golden document. Realistic values, stable across runs — this
                       is what Lane B imports (or reads from `run_view_fixture.json`).
    fixture_run()      the same document GENERATED by the real `assemble_view`, from a real loop
                       over fake actuators. If the envelope changes, this changes with it.

`key_shape()` is how the two are compared: structure, not timings. A production record's latency
and a run's timestamps are genuinely different on every run, and a fixture test that failed on
those would be a test everybody learns to re-record without reading.

NO GPU, NO NETWORK, NO DATABASE. The actuators here are local fakes that behave exactly as a real
producer does at the seam that matters — they append a STAMPED descriptor to the execution
context's quarantine (PROV-001) and return an `ActuatorResult`. Nothing is monkeypatched, so this
module is importable from a script, a test, or a Lane B tooling step.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Mapping

from backend.services import epistemics
from backend.services.director import run_surface as rs
from backend.services.director.capabilities import get as get_actuator
from backend.services.director.execution import OK, ActuatorResult
from backend.services.director.planner import RuleBasedPlanner

FIXTURE_PATH = Path(__file__).with_suffix(".json")

FIXTURE_RUN_ID = "run_fixture01"
FIXTURE_PROMPT = "read the material of the surface"
FIXTURE_POSTS = ("507f1f77bcf86cd799439021", "507f1f77bcf86cd799439022")


# ── the fake actuator, at the one seam that matters ──────────────────────────

class _FixtureRunner:
    """An actuator that produces a stamped suggestion and nothing else.

    It exists to exercise the REAL path from a step to a descriptor: the descriptor carries its
    producer, its model, the run, and — the join PROV-001 added — the step. A stub that skipped
    that would make the fixture a picture of a run that never had provenance.
    """

    def __init__(self, name: str, ctx: Any):
        self.name = name
        self.ctx = ctx

    def __call__(self, step, memory) -> ActuatorResult:
        actuator = get_actuator(self.name)
        if actuator is None:
            return ActuatorResult(status="unavailable", produced=(), adapter=self.name)
        sug = epistemics.stamp({
            "producer": self.name,
            "type": "brush_field",
            "role": self.name,
            "post_id": self.ctx.post_id,
            "geometry": {"kind": "soft_mask",
                         "strokes": [{"points": [[0.5, 0.5]], "radius": 0.05}]},
            "provenance": {"model": f"fixture::{self.name}", "adapter": self.name,
                           "run_id": self.ctx.run_id, "step_id": step.id},
            "confidence": 0.62,
        })
        self.ctx.suggestions.append(sug)
        return ActuatorResult(status=OK, produced=tuple(actuator.produces), confidence=0.62,
                              model=f"fixture::{self.name}", adapter=self.name,
                              detail=f"produced 1 suggestion(s)")


def _registry_for(ctx_of):
    from backend.services.director.capabilities import known

    def _for(post_id: str) -> Dict[str, Any]:
        ctx = ctx_of(post_id)
        return {name: _FixtureRunner(name, ctx) for name in known()}
    return _for


def fixture_posts() -> Dict[str, Dict[str, Any]]:
    """Two RAW posts — a picture each and no annotations at all. The fixture is annotation-
    independent for the same reason the surface is: it is the case that must work."""
    return {pid: {"_id": pid, "photo_url": f"https://example.invalid/{n}.jpg",
                  "title": ("Facade" if n == 0 else "Rotunda")}
            for n, pid in enumerate(FIXTURE_POSTS)}


def fixture_run() -> rs.RunView:
    """A real run, assembled by the real assembler. The generated half of the fixture."""
    posts = fixture_posts()
    spec = rs.RunSpec.of(prompt=FIXTURE_PROMPT, image_ids=list(FIXTURE_POSTS))
    engine = rs.build_engine(spec, posts, run_id=FIXTURE_RUN_ID, planner=RuleBasedPlanner())
    engine.registry = rs.routed_registry(
        engine.ctx, registry_for=_registry_for(lambda pid: engine.ctx.contexts[pid]))
    result = rs.lc.run_loop(spec.prompt, engine.memory, engine.registry,
                            director=engine.director, max_rounds=2, loop_id=FIXTURE_RUN_ID,
                            resolve_fn=engine.resolver)
    view = rs.assemble_view(spec, result, engine, run_id=FIXTURE_RUN_ID,
                            now="2026-08-01T12:00:00+00:00")
    engine.close()
    return view


# ── comparing shapes, not timings ────────────────────────────────────────────

#: Fields whose value is genuinely different on every run. Compared for PRESENCE and TYPE, never
#: for equality — a fixture test that failed on a clock is one nobody reads before re-recording.
VOLATILE = ("latency_ms", "created_at", "updated_at")


def key_shape(value: Any) -> Any:
    """The structure of a document: keys, nesting, and list element shapes — no leaf values.

    This is what "serialises to the fixture" is allowed to mean. Two runs of the same prompt will
    differ in confidences, ids and durations; if they differ in SHAPE, the contract moved and both
    lanes need to know.
    """
    if isinstance(value, Mapping):
        return {k: key_shape(v) for k, v in sorted(value.items())}
    if isinstance(value, (list, tuple)):
        return [key_shape(v) for v in value[:1]]        # one element defines the element shape
    return type(value).__name__ if value is not None else "None"


def load_json() -> Dict[str, Any]:
    """The committed JSON, for a Lane B tool that would rather read a file than import python."""
    return json.loads(FIXTURE_PATH.read_text())


def write_json(view: rs.RunView | None = None) -> Path:
    """Re-record the JSON half from the generated half. Run deliberately, never in a test."""
    payload = (view or fixture_run()).to_dict()
    FIXTURE_PATH.write_text(json.dumps(payload, indent=2, sort_keys=True, default=str) + "\n")
    return FIXTURE_PATH


#: The committed golden document. Generated by `write_json()` and read back here, so the literal
#: Lane B imports and the file it may read instead can never disagree.
RUN_VIEW_FIXTURE: Dict[str, Any] = load_json() if FIXTURE_PATH.exists() else {}
