// PERCEPTUAL-FORMS-001E — the fixtures, and where they come from.
//
// THE CONTRACT PAYLOADS ARE NOT RE-AUTHORED HERE. `formPayloads.json` beside this file is a
// bundle of the nineteen committed payloads at `contracts/fixtures/perception-lab/forms/`,
// keyed by form. It exists for one reason: the Vercel project uploads `frontend/` as its
// deployment source, so a browser bundle cannot import from the repo root — the same reason
// `frontend/src/contracts/perception-lab.v1.json` exists. It is regenerated, never edited:
//
//     UPDATE_FORM_FIXTURES=1 npx vitest run src/perceptionLab/forms/formFixtureDrift
//
// and `formFixtureDrift.test.js` fails when it and the canonical files disagree. A copy that
// nothing pins is a second contract with a head start.
//
// THE OTHER SCENARIOS ARE DERIVED, AND THE DERIVATION IS THE HONEST PART. The build asks for
// dense and empty states. Hand-authoring nineteen more payloads would produce nineteen more
// things that can drift from the grammar; instead each extra scenario is a small, visible,
// deterministic transformation of the committed one, so a change to the contract payload flows
// into every state automatically and no scenario can quietly stop being a valid record.
//
// FOUR STATES PER FORM, and each is a distinct finding the contract insists is not the others:
//
//   contract   the committed payload, exactly.
//   empty      the collection emptied, THE EXAMINATION COUNTER KEPT. "Looked and found nothing"
//              is a measurement. Dropping the counter with the contents would turn it into
//              "nothing here", which is the `empty_is_not_refused_is_not_unavailable` law's
//              whole subject.
//   dense      enough members to break a layout that was only ever tested with two.
//   withheld   fields only: the values replaced by a `data_ref` this page cannot read. The
//              renderer must refuse rather than draw a gradient from the statistics.
//
// NO RANDOMNESS ANYWHERE. Every dense scenario is generated by an index arithmetic so the same
// fixture produces the same picture in every run and in every screenshot.

import PAYLOADS from './formPayloads.json';

/** The nineteen committed payloads, keyed by form. Frozen: this is a mirror, not a workspace. */
export const FORM_PAYLOADS = Object.freeze(PAYLOADS);

/**
 * The image these fixtures describe.
 *
 * There is no photograph. The stage draws a token-coloured plate with a rule grid instead, and
 * says so: a lab whose backdrop is a picture invites people to judge whether a mask "looks right"
 * against a subject, and these masks are 8×8 test rasters that describe nothing. The grid makes
 * the only readable thing on the stage the geometry, which is the only thing here that is real.
 *
 * The declared size is a real 4:3 frame because the letterbox contract has to be exercised: an
 * 8×8 square raster normalized [0,1] and drawn into a 4:3 viewBox is precisely the case where a
 * surface that reimplements `object-fit: contain` puts the shape in the wrong place.
 */
export const FIXTURE_SOURCE = Object.freeze({
    natural_width: 1600,
    natural_height: 1200,
    label: 'a 1600×1200 frame with no photograph in it',
    note: 'The ground is a rule grid, not an image. These fixtures carry 8×8 and 4×4 rasters, '
        + 'which describe no subject — drawing them over a photograph would invite a judgement '
        + 'about whether a mask "looks right" that the fixture cannot support.',
});

const clone = (v) => JSON.parse(JSON.stringify(v));

/** The list field each payload variant carries, and the counter that says it looked. */
const COLLECTION = Object.freeze({
    extent_set: 'instances',
    extent_boundary: 'boundaries',
    extent_hole_set: 'holes',
    extent_soft_field: null,
    extent_fragment_set: 'fragments',
    extent_fusion_hypothesis: 'hypotheses',
    extent_partition: 'regions',
    extent_hierarchy: 'nodes',
    extent_density_field: 'members',
    extent_hypothesis_set: 'alternatives',
    topology_relation_set: 'relations',
    topology_contact_locus: 'loci',
    topology_intersection: 'intersections',
    topology_clearance_path: 'paths',
    topology_containment_tree: 'nodes',
    topology_adjacency_graph: 'nodes',
    negative_space_field: 'figure_instance_ids',
    topology_transition: 'transitions',
    topology_uncertain_relations: 'relations',
});

/** Empty the collection and keep everything that records the looking. */
function emptied(payload) {
    const out = clone(payload);
    const key = COLLECTION[out.variant];
    if (key && Array.isArray(out[key])) out[key] = [];
    if (Array.isArray(out.edges)) out.edges = [];
    if (out.variant === 'extent_hierarchy' || out.variant === 'topology_containment_tree') {
        out.root_node_ids = [];
    }
    return out;
}

/* ── the dense generators ────────────────────────────────────────────────── */

// A deterministic 8×8 RLE for a k-th small square, so a dense extent scenario carries real
// decodable masks rather than boxes standing in for them.
function squareRle(index) {
    const col = index % 3;
    const row = Math.floor(index / 3) % 3;
    const x0 = 1 + col * 2;
    const y0 = 1 + row * 2;
    // Column-major runs, first run zeros: for each of two columns, y0 zeros then 2 ones.
    const counts = [x0 * 8 + y0, 2, 8 - 2, 2];
    counts.push(64 - counts.reduce((a, b) => a + b, 0));
    return { size: [8, 8], counts };
}

const box = (i, n) => ({
    x: 0.06 + ((i % 5) * 0.18),
    y: 0.06 + (Math.floor(i / 5) % 4) * 0.22,
    w: 0.14,
    h: 0.16,
    _n: n,
});

function densify(payload, count) {
    const out = clone(payload);
    switch (out.variant) {
    case 'extent_set':
        out.instances = Array.from({ length: count }, (_, i) => ({
            instance_id: `inst_d${i + 1}`,
            mask_rle: i % 3 === 0 ? squareRle(i) : null,
            box: (({ x, y, w, h }) => ({ x, y, w, h }))(box(i, count)),
            area: 0.02 + (i % 4) * 0.01,
            confidence: null,
            naming: i % 2 === 0
                ? { text: `figure ${i + 1}`, source: 'prompt', epistemic_status: 'interpretive',
                    confidence: 0.4 + (i % 6) * 0.08 }
                : null,
            region_id: null,
            geometry_rev: null,
        }));
        out.searched = 'every separable instance in the whole image';
        out.dropped_below_min_area = 4;
        break;
    case 'extent_fragment_set':
        out.fragments = Array.from({ length: count }, (_, i) => ({
            fragment_id: `frag_d${i + 1}`,
            mask_rle: i % 4 === 0 ? squareRle(i) : null,
            box: (({ x, y, w, h }) => ({ x, y, w, h }))(box(i, count)),
            area: 0.01 + (i % 3) * 0.005,
            naming: null,
        }));
        out.regions_examined = count * 2;
        break;
    case 'extent_hierarchy':
    case 'topology_containment_tree': {
        const nodes = [];
        const isExtent = out.variant === 'extent_hierarchy';
        for (let i = 0; i < count; i += 1) {
            const parent = i === 0 ? null : `n${Math.floor((i - 1) / 2)}`;
            const node = {
                node_id: `n${i}`,
                parent_node_id: parent,
                occupancy_of_parent: parent ? Math.round((0.9 / (1 + (i % 5))) * 100) / 100 : null,
                basis: i % 3 === 2 ? 'box' : 'mask',
            };
            if (isExtent) {
                node.instance = { artifact_id: 'art_extent_dense', instance_id: `inst_${i}`,
                    geometry_rev: i % 3 };
                node.region = null;
            } else {
                node.endpoint = { artifact_id: 'art_extent_dense', instance_id: `inst_${i}`,
                    scope: 'session', region_id: null, geometry_rev: null };
                node.epistemic_status = i % 3 === 2 ? 'interpretive' : 'measured';
            }
            nodes.push(node);
        }
        out.nodes = nodes;
        out.root_node_ids = ['n0'];
        out.pairs_examined = count * (count - 1) / 2;
        break;
    }
    case 'topology_relation_set': {
        const KINDS = ['contains', 'disjoint', 'meets', 'overlaps', 'nested_within', 'in_front_of'];
        const DIRECTED = new Set(['contains', 'nested_within', 'in_front_of']);
        out.relations = Array.from({ length: count }, (_, i) => {
            const kind = KINDS[i % KINDS.length];
            return {
                relation_id: `rel_d${i + 1}`,
                kind,
                source: { artifact_id: 'art_extent_dense', instance_id: `inst_${i % 6}`,
                    scope: 'session', region_id: null, geometry_rev: null },
                target: { artifact_id: 'art_extent_dense', instance_id: `inst_${(i + 3) % 6}`,
                    scope: 'session', region_id: null, geometry_rev: null },
                directed: DIRECTED.has(kind),
                basis: i % 4 === 3 ? 'box' : 'mask',
                epistemic_status: i % 4 === 3 ? 'interpretive' : 'measured',
                measurements: kind === 'disjoint'
                    ? { separation: Math.round((0.05 + (i % 7) * 0.03) * 1000) / 1000 }
                    : { containment_fraction: Math.round((0.4 + (i % 6) * 0.1) * 100) / 100 },
                stale: i % 9 === 8,
            };
        });
        out.pairs_examined = count * 2;
        break;
    }
    case 'topology_adjacency_graph': {
        out.nodes = Array.from({ length: count }, (_, i) => ({
            node_id: `pier_${i + 1}`,
            endpoint: { artifact_id: 'art_extent_dense', instance_id: `inst_pier_${i + 1}`,
                scope: 'session', region_id: null, geometry_rev: null },
        }));
        const edges = [];
        for (let i = 0; i < count; i += 1) {
            for (const step of [1, 3]) {
                const j = (i + step) % count;
                if (j <= i) continue;
                edges.push({
                    edge_id: `edge_${i + 1}_${j + 1}`,
                    source_node_id: `pier_${i + 1}`,
                    target_node_id: `pier_${j + 1}`,
                    kind: step === 1 ? 'meets' : 'disjoint',
                    directed: false,
                    basis: 'mask',
                    epistemic_status: 'measured',
                    measurements: step === 1
                        ? { contact_pixels: 100 + i * 7 } : { separation: 0.1 + i * 0.01 },
                    locus_artifact_id: step === 1 && i === 0 ? 'art_locus_1' : null,
                });
            }
        }
        out.edges = edges;
        out.pairs_examined = count * (count - 1) / 2;
        break;
    }
    case 'extent_hypothesis_set': {
        const weights = Array.from({ length: count }, (_, i) => 1 / (i + 2));
        const total = weights.reduce((a, b) => a + b, 0);
        out.alternatives = weights.map((w, i) => ({
            alternative_id: `alt_d${i + 1}`,
            weight: Math.round((w / total) * 1000) / 1000,
            artifact_id: null,
            instances: [{ artifact_id: 'art_fragments_dense', instance_id: `frag_${i + 1}` }],
            grounds: [{ kind: ['shape_continuity', 'depth_continuity', 'relative_position',
                'appearance_continuity'][i % 4],
            detail: `ground ${i + 1}`, cites: [], strength: null }],
        }));
        out.alternatives_considered = count;
        break;
    }
    default:
        // Forms whose dense case adds nothing a person could not see in the committed payload —
        // a single field, a single partition — keep it rather than inventing a crowd.
        break;
    }
    return out;
}

/** Replace a field's inline values with a ref this page cannot read. */
function withheld(payload) {
    const out = clone(payload);
    const strip = (field) => {
        if (!field) return field;
        field.inline_values = null;
        field.data_ref = { uri: 'semant://fields/withheld', digest: 'sha256:0000',
            media_type: 'application/octet-stream', bytes: 4096 };
        return field;
    };
    if (out.field) strip(out.field);
    if (Array.isArray(out.regions)) out.regions.forEach((r) => strip(r.field));
    if (out.variant === 'negative_space_field') out.field_ref = { uri: 'semant://fields/withheld',
        digest: 'sha256:0000', media_type: 'application/octet-stream', bytes: 4096 };
    return out;
}

const HAS_FIELD = new Set([
    'extent.soft_field', 'extent.density_field', 'extent.visible_inferred_partition',
    'topology.negative_space_field',
]);

const DENSE_COUNT = Object.freeze({
    'extent.hard_mask': 18,
    'extent.fragment_set': 14,
    'extent.hierarchy': 15,
    'extent.hypothesis_set': 6,
    'topology.pair_relation': 18,
    'topology.containment_tree': 15,
    'topology.adjacency_graph': 8,
});

/**
 * Every scenario, for every form. `{[formKey]: {[scenarioKey]: payload}}`.
 *
 * Built once at module load and frozen. A renderer test that mutated a payload in place would
 * otherwise leak into every later test in the file, and the resulting failure would look like a
 * renderer bug rather than a shared-fixture bug.
 */
export const SCENARIOS = Object.freeze(Object.fromEntries(
    Object.entries(FORM_PAYLOADS).map(([key, payload]) => {
        const scenarios = { contract: payload, empty: emptied(payload) };
        if (DENSE_COUNT[key]) scenarios.dense = densify(payload, DENSE_COUNT[key]);
        if (HAS_FIELD.has(key)) scenarios.withheld = withheld(payload);
        if (key === 'topology.negative_space_field') scenarios.resolvable = resolvableFigures(payload);
        return [key, Object.freeze(scenarios)];
    })));

/**
 * The negative-space payload, pointed at figures this fixture set can actually resolve.
 *
 * WHY THIS SCENARIO HAD TO BE INVENTED, which is a finding rather than a convenience. The
 * `negative_space_field` variant has no inline-values escape hatch: the field lives behind
 * `field_ref` and nowhere else. So its declared `scalar_wash` projection is UNDRAWABLE by any
 * runtime that cannot fetch that ref, which this one cannot — the committed payload's wash view
 * is permanently absent, correctly and uselessly.
 *
 * The only honest picture available is the one Lane E's `deriveNegativeSpaceField` already
 * computes: a distance transform run in this browser over the figure masks, truncated at the same
 * `max_distance_used` the record declared, and stamped `derived`. That needs figures the set can
 * resolve, and the committed payload names two buildings it cannot. So this scenario renames them
 * to the two instances `extent.hard_mask` does carry — and every layer it produces is `derived`,
 * beside the measured one that is still absent. That side-by-side IS the demonstration.
 */
function resolvableFigures(payload) {
    const out = clone(payload);
    out.figure_instance_ids = ['inst_1', 'inst_2'];
    out.field_shape = [8, 8];
    return out;
}

/** The scenario keys a form offers, in a fixed order, for the picker and for the tests. */
export const ORDER = Object.freeze(['contract', 'resolvable', 'empty', 'dense', 'withheld']);
export const scenariosFor = (formKey) => ORDER.filter((k) => SCENARIOS[formKey]?.[k]);
export const payloadFor = (formKey, scenario = 'contract') => SCENARIOS[formKey]?.[scenario] ?? null;

export const SCENARIO_NOTE = Object.freeze({
    contract: 'the payload committed at contracts/fixtures/perception-lab/forms/, unchanged',
    resolvable: 'the same record, pointed at the two instances this fixture set carries geometry '
        + 'for, so the browser-derived field can be computed and shown beside the measured one '
        + 'that is not on this page',
    empty: 'the collection emptied and the examination counter kept — this form looked and found '
        + 'nothing, which is a measurement and not a failure',
    dense: 'enough members to break a layout that was only tested with two',
    withheld: 'the field values replaced by a data_ref this page cannot read',
});
