#!/usr/bin/env python3
"""
PERCEPTUAL-ORGANS-002 Lane C — the synthetic controls the Topology façade is tested against.

WHY SYNTHETIC, when the corpus is full of real masks. Because a control has to be a case whose
answer is known before the organ runs. A rectangle ten pixels inside another rectangle IS contained;
two rectangles sharing a column DO meet; two rectangles at opposite corners are apart by a distance
arithmetic can state. When the façade disagrees with one of these, the façade is wrong — there is no
third possibility to argue about, which is exactly what a real photograph cannot give you. The
master plan asks for these by name: "simple synthetic containment/contact/overlap/disjoint
controls".

Every scene is written as a CONTRACT-SHAPED `extent_set` artifact, validated through
`PerceptualArtifact` before it is written, because a fixture that does not satisfy the merged
contract would test this lane against a shape no other lane will ever send it.

    python scripts/perception_lab_topology_fixtures.py            # write them
    python scripts/perception_lab_topology_fixtures.py --check    # exit 1 if they have drifted

`backend/tests/test_perception_lab_topology.py` runs `--check` by name, so a scene edited here and
not regenerated fails the suite rather than quietly diverging from the JSON the tests read.

THE DEPTH FIELDS ARE FIXTURES TOO, and that is the whole point of them. `topology.occlusion`
consumes a PREPARED depth field and this laboratory cannot compute one; a committed field is what
lets the seam be exercised without a model, and its provenance says `fixture` in the one place a
reader looks for it.

Writes nothing outside `research/perception_lab/fixtures/topology/`. No database, no network,
no model.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from backend.schemas.perception_lab import PerceptualArtifact  # noqa: E402
from backend.services import mask_geometry as mg  # noqa: E402

FIXTURE_DIR = REPO_ROOT / "research" / "perception_lab" / "fixtures" / "topology"

#: Small on purpose. Every measurement below walks every pixel in pure Python, and a 40x60 frame
#: keeps the whole suite under a second while leaving room for a shape to be unambiguously inside,
#: beside, or far from another. The masks are still real COCO RLE — the round trip is exact at any
#: size, and a fixture that faked the encoding would test the fake.
H, W = 40, 60

DIGEST = "sha256:70909a17c0d5e4b2"

README = """\
# Topology controls (generated)

Synthetic scenes for `backend/services/perception_lab/topology.py`, generated by
`scripts/perception_lab_topology_fixtures.py`. Do not edit them by hand — edit the script and
re-run it; `backend/tests/test_perception_lab_topology.py` runs `--check` and fails if they drift.

Each `extent-set.*.json` is a contract-shaped `PerceptualArtifact` holding an `extent_set` whose
instances are rectangles on a 40x60 raster, so the right answer is known before the organ runs:

| scene | what it controls |
|---|---|
| `containment` | one rectangle wholly inside another, with room to spare |
| `contact` | two rectangles sharing a column — they meet, and nothing overlaps |
| `overlap` | two rectangles crossing — a known intersection area |
| `disjoint` | two rectangles at opposite corners — a known separation |
| `scene` | four instances, for bounded all-pairs |
| `box-only` | no masks at all: the box basis, and its lower ceiling |
| `empty-mask` | a structurally valid RLE with zero set pixels — a refusal |
| `other-raster` | two instances on different rasters — no shared grid |
| `canonical` | instances citing canonical region ids AND `geometry_rev` |

`depth-field.*.json` are PREPARED depth fields in the shape `backend/services/depth_organ.py`
accepts. Nothing in the Perception Lab can produce one; `topology.occlusion` consumes them or
refuses `missing_depth_artifact`.
"""


# ── rectangles → real RLE ────────────────────────────────────────────────────


def rect_bits(rects: Sequence[Tuple[int, int, int, int]], h: int = H, w: int = W) -> bytearray:
    """Row-major bits with every `(x0, x1, y0, y1)` half-open rectangle set."""
    bits = bytearray(h * w)
    for x0, x1, y0, y1 in rects:
        for y in range(max(0, y0), min(h, y1)):
            row = y * w
            for x in range(max(0, x0), min(w, x1)):
                bits[row + x] = 1
    return bits


def rect_rle(rects: Sequence[Tuple[int, int, int, int]], h: int = H, w: int = W) -> Dict[str, Any]:
    return mg.rle_encode(rect_bits(rects, h, w), h, w)


def norm_box(x0: int, x1: int, y0: int, y1: int, h: int = H, w: int = W) -> Dict[str, float]:
    return {"x": round(x0 / w, 6), "y": round(y0 / h, 6),
            "w": round((x1 - x0) / w, 6), "h": round((y1 - y0) / h, 6)}


def instance(instance_id: str, *, rects: Optional[Sequence[Tuple[int, int, int, int]]] = None,
             box: Optional[Dict[str, float]] = None, h: int = H, w: int = W,
             region_id: Optional[str] = None,
             geometry_rev: Optional[int] = None) -> Dict[str, Any]:
    rle = rect_rle(rects, h, w) if rects is not None else None
    area = None
    if rle is not None:
        area = round(mg.rle_area(rle) / float(h * w), 6)
    return {
        "instance_id": instance_id,
        "mask_rle": rle,
        "box": box if box is not None else (
            mg.rle_bbox_norm(rle) if rle is not None and mg.rle_area(rle) else None),
        "area": area,
        "confidence": None,
        "naming": None,
        "region_id": region_id,
        "geometry_rev": geometry_rev,
    }


def extent_set(artifact_id: str, *, searched: str, instances: List[Dict[str, Any]],
               basis: str = "mask", status: str = "measured") -> Dict[str, Any]:
    """One scene, as the `extent_set` artifact a topology operation consumes.

    `operation` is `extent.reuse` and `producer_kind` is `fixture` because that is what these are:
    committed geometry, reused. Naming a segmenter here would make a hand-written rectangle
    indistinguishable from a mask a model produced, in every later report.
    """
    return {
        "identity": {
            "artifact_id": artifact_id, "session_id": "labs_topology_fixture",
            "run_id": "run_fixture_topology", "step_id": "step_extent",
            "organ_family": "extent", "artifact_kind": "extent_set",
            "operation": "extent.reuse", "identity_scope": "session",
            "identity_refs": [
                {"region_id": i["region_id"], "geometry_rev": i["geometry_rev"],
                 "scope": "canonical"}
                for i in instances if i.get("region_id")],
            "input_refs": [], "derived_from": [],
        },
        "measurement": {
            "payload_variant": "extent_set",
            "payload": {"variant": "extent_set", "searched": searched, "instances": instances,
                        "dropped_below_min_area": None, "duplicates": [], "comparison": None},
            "data_ref": None, "coordinate_system": "normalized_xy_topleft",
            "epistemic_status": status, "epistemic_basis": basis,
            "basis_detail": f"synthetic control geometry on a {H}x{W} raster",
        },
        "projection": {"projection_kind": "mask_fill",
                       "hints": {"opacity": 0.35, "palette_role": "figure"}},
        "interpretation": {"label": None, "label_source": "none",
                           "epistemic_status": "uncertain",
                           "notes": "a control scene: rectangles, and no claim about any picture"},
        "lifecycle": {"status": "proposed", "changed_at": "2026-08-10T12:00:00Z",
                      "changed_by": "perception_lab_fixture"},
        "provenance": {
            "producer_kind": "fixture", "producer": "perception_lab_topology_fixtures",
            "adapter": None, "model": None, "revision": None,
            "source_image_digest": DIGEST, "started_at": None, "completed_at": None,
            "duration_ms": None, "device": None, "peak_memory_mb": None,
        },
    }


# ── the scenes ───────────────────────────────────────────────────────────────

#: The rectangles, named once so the tests can import the same numbers the fixtures were built from
#: rather than restating them. A test that hardcoded `100` for the intersection area would pass
#: after someone moved a rectangle and stopped measuring what it says it measures.
RECTS: Dict[str, Tuple[int, int, int, int]] = {
    "outer": (5, 55, 5, 35),
    "inner": (20, 30, 15, 25),
    "left": (5, 25, 10, 30),
    "right": (25, 45, 10, 30),
    "cross_a": (10, 30, 10, 30),
    "cross_b": (20, 40, 20, 40),
    "far_a": (2, 12, 3, 13),
    "far_b": (45, 58, 26, 36),
}

#: The bounded set for all-pairs: an outer shape, something nested in it, something abutting it,
#: and something plainly away from all three. Four members is six unordered pairs.
SCENE: Dict[str, Tuple[int, int, int, int]] = {
    "scene_outer": (5, 40, 5, 30),
    "scene_inner": (15, 25, 12, 22),
    "scene_touching": (40, 55, 8, 24),
    "scene_far": (5, 20, 34, 40),
}


def scenes() -> Dict[str, Dict[str, Any]]:
    out: Dict[str, Dict[str, Any]] = {}

    out["extent-set.containment.json"] = extent_set(
        "art_topo_containment", searched="a control: one rectangle wholly inside another",
        instances=[instance("inst_inner", rects=[RECTS["inner"]]),
                   instance("inst_outer", rects=[RECTS["outer"]])])

    out["extent-set.contact.json"] = extent_set(
        "art_topo_contact", searched="a control: two rectangles sharing a column",
        instances=[instance("inst_left", rects=[RECTS["left"]]),
                   instance("inst_right", rects=[RECTS["right"]])])

    out["extent-set.overlap.json"] = extent_set(
        "art_topo_overlap", searched="a control: two rectangles crossing",
        instances=[instance("inst_a", rects=[RECTS["cross_a"]]),
                   instance("inst_b", rects=[RECTS["cross_b"]])])

    out["extent-set.disjoint.json"] = extent_set(
        "art_topo_disjoint", searched="a control: two rectangles at opposite corners",
        instances=[instance("inst_a", rects=[RECTS["far_a"]]),
                   instance("inst_b", rects=[RECTS["far_b"]])])

    out["extent-set.scene.json"] = extent_set(
        "art_topo_scene", searched="a control: four instances for a bounded all-pairs graph",
        instances=[instance("inst_outer", rects=[SCENE["scene_outer"]]),
                   instance("inst_inner", rects=[SCENE["scene_inner"]]),
                   instance("inst_touching", rects=[SCENE["scene_touching"]]),
                   instance("inst_far", rects=[SCENE["scene_far"]])])

    # No masks anywhere: the finial-in-the-sky shape, where a box containment reads ~1.0 and the
    # ceiling keeps it `interpretive`.
    out["extent-set.box-only.json"] = extent_set(
        "art_topo_box", searched="a control: boxes and no masks",
        instances=[instance("inst_inner", box=norm_box(*RECTS["inner"])),
                   instance("inst_outer", box=norm_box(*RECTS["outer"]))],
        basis="box", status="interpretive")

    # A structurally VALID rle whose runs sum to h*w and set nothing. This is the case a validator
    # cannot catch and only a decoder can.
    out["extent-set.empty-mask.json"] = extent_set(
        "art_topo_empty", searched="a control: a valid RLE with no set pixels",
        instances=[
            {**instance("inst_empty", rects=[]), "box": norm_box(*RECTS["inner"])},
            instance("inst_solid", rects=[RECTS["outer"]])])

    out["extent-set.other-raster.json"] = extent_set(
        "art_topo_other_raster", searched="a control: two instances on different rasters",
        instances=[instance("inst_full", rects=[RECTS["inner"]]),
                   instance("inst_small", rects=[(5, 15, 5, 12)], h=20, w=30)])

    out["extent-set.canonical.json"] = extent_set(
        "art_topo_canonical",
        searched="a control: instances that cite canonical regions AND their revisions",
        instances=[instance("inst_finial", rects=[RECTS["inner"]],
                            region_id="reg_finial_7", geometry_rev=4),
                   instance("inst_sky", rects=[RECTS["outer"]],
                            region_id="reg_sky_1", geometry_rev=2)])
    return out


# ── prepared depth fields ────────────────────────────────────────────────────

#: `depth_organ.SOURCE_ADAPTER`. Restated as a literal rather than imported so that a fixture is a
#: fixture: if the organ ever changes which checkpoint it accepts, these files should FAIL to be
#: read rather than silently follow it, because they were not produced by the new one either.
DEPTH_ADAPTER = "depth_anything_v2_small"
DEPTH_GRID = 16


def depth_field(name: str, *, near_rects: Sequence[Tuple[int, int, int, int]], near: float,
                far: float, note: str) -> Dict[str, Any]:
    """A coarse inverse-depth grid: larger is nearer, exactly as Depth-Anything reports it.

    Cells are marked near where the given rectangles cover the cell's centre, which is all the
    resolution a 16x16 grid over a 40x60 frame has. Enough for an ordering statistic, which is what
    occlusion reads and the only thing this field is for.
    """
    values: List[float] = []
    for gy in range(DEPTH_GRID):
        cy = (gy + 0.5) * H / DEPTH_GRID
        for gx in range(DEPTH_GRID):
            cx = (gx + 0.5) * W / DEPTH_GRID
            hit = any(x0 <= cx < x1 and y0 <= cy < y1 for x0, x1, y0, y1 in near_rects)
            values.append(near if hit else far)
    return {
        "name": name,
        "note": note,
        "artifact_id": f"depth_{name}",
        "field": {
            "depth": values, "grid": DEPTH_GRID, "adapter": DEPTH_ADAPTER,
            "model": "Depth-Anything-V2-Small-hf",
            "revision": "5426e4f0f36572d16453bbda7a8389317b1bef99",
            "preprocessing_version": "depth-anything-v2-s-v1", "whole_frame": True,
        },
    }


def depth_fields() -> Dict[str, Dict[str, Any]]:
    return {
        # The finial case, in miniature: the inner rectangle reads nearer than everything around
        # it, so an ordering statistic separates the pair even though both lie inside one box.
        "depth-field.inner-in-front.json": depth_field(
            "inner_in_front", near_rects=[RECTS["inner"]], near=0.9, far=0.1,
            note="the inner rectangle is nearer than the outer one"),
        # Nothing to order. The organ's own floor decides, and the answer is `coplanar` — which is
        # NOT a claim of containment, as `occlusion_organ` is at pains to say.
        "depth-field.flat.json": depth_field(
            "flat", near_rects=[], near=0.5, far=0.5,
            note="one depth everywhere: no ordering to find"),
        # Same shape, another checkpoint. `depth_organ.assert_field_valid` refuses it, and the
        # façade relays the refusal instead of reading a grid from a model it did not expect.
        "depth-field.foreign-adapter.json": {
            **depth_field("foreign_adapter", near_rects=[RECTS["inner"]], near=0.9, far=0.1,
                          note="a depth grid from another model — must not read as this one"),
            "field": {**depth_field("foreign_adapter", near_rects=[RECTS["inner"]], near=0.9,
                                    far=0.1, note="")["field"],
                      "adapter": "some_other_depth_model"},
        },
    }


# ── write / check ────────────────────────────────────────────────────────────


def build() -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for name, artifact in scenes().items():
        PerceptualArtifact.model_validate(artifact)   # a fixture that fails the contract is a bug
        out[name] = artifact
    out.update(depth_fields())
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed fixtures differ from what this would write")
    args = parser.parse_args()

    files = build()
    files["README.md"] = README

    if args.check:
        drifted: List[str] = []
        for name, content in files.items():
            path = FIXTURE_DIR / name
            expected = content if isinstance(content, str) else json.dumps(content, indent=2) + "\n"
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                drifted.append(name)
        stale = sorted(p.name for p in FIXTURE_DIR.glob("*")
                       if p.is_file() and p.name not in files)
        if drifted or stale:
            print("topology fixtures have drifted:", file=sys.stderr)
            for name in drifted:
                print(f"  regenerate {name}", file=sys.stderr)
            for name in stale:
                print(f"  no longer generated: {name}", file=sys.stderr)
            print("run: python scripts/perception_lab_topology_fixtures.py", file=sys.stderr)
            return 1
        print(f"{len(files)} topology fixtures are current")
        return 0

    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        text = content if isinstance(content, str) else json.dumps(content, indent=2) + "\n"
        (FIXTURE_DIR / name).write_text(text, encoding="utf-8")
    print(f"wrote {len(files)} files to {FIXTURE_DIR.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
